// @ts-nocheck
// Auto-generated by tauri-specta

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	readFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_file", { path })),
	writeFile: (path: string, content: string) => typedError<null, string>(__TAURI_INVOKE("write_file", { path, content })),
	/**
	 *  Returns the detected encoding for a file that was previously read via `read_file`.
	 *  Returns `"UTF-8"` if the file is UTF-8 (or was never read).
	 */
	getFileEncoding: (path: string) => typedError<string, string>(__TAURI_INVOKE("get_file_encoding", { path })),
	listDirectory: (path: string, showHidden: boolean | null) => typedError<FileEntry[], string>(__TAURI_INVOKE("list_directory", { path, showHidden })),
	createFile: (parentDir: string, filename: string) => typedError<string, string>(__TAURI_INVOKE("create_file", { parentDir, filename })),
	/**
	 *  Create a scratch file in ~/.cache/novelist/ for single-file mode.
	 *  Filename pattern: `novelist_scratch_<unix_millis>.md`
	 *  This pattern is checked by the frontend to detect unsaved scratch files.
	 *  Returns the absolute path of the created file.
	 */
	createScratchFile: () => typedError<string, string>(__TAURI_INVOKE("create_scratch_file")),
	createDirectory: (parentDir: string, name: string) => typedError<string, string>(__TAURI_INVOKE("create_directory", { parentDir, name })),
	/**
	 *  Rename a file or folder in place.
	 *  When `allow_collision_bump` is Some(true), appends " 2", " 3", … on collision.
	 *  Defaults to error-on-collision when None or Some(false).
	 */
	renameItem: (oldPath: string, newName: string, allowCollisionBump: boolean | null) => typedError<string, string>(__TAURI_INVOKE("rename_item", { oldPath, newName, allowCollisionBump })),
	// Emit a global Tauri event so other windows can update their tab state.
	broadcastFileRenamed: (oldPath: string, newPath: string) => typedError<null, string>(__TAURI_INVOKE("broadcast_file_renamed", { oldPath, newPath })),
	/**
	 *  Move a file or folder into `target_dir`. Auto-numbers on collision
	 *  ("a.md" -> "a 2.md"). Rejects moving a folder into its own descendant.
	 */
	moveItem: (sourcePath: string, targetDir: string) => typedError<string, string>(__TAURI_INVOKE("move_item", { sourcePath, targetDir })),
	deleteItem: (path: string) => typedError<null, string>(__TAURI_INVOKE("delete_item", { path })),
	checkPandoc: () => typedError<PandocStatus, string>(__TAURI_INVOKE("check_pandoc")),
	exportProject: (inputFiles: string[], outputPath: string, format: string, extraArgs: string[]) => typedError<string, string>(__TAURI_INVOKE("export_project", { inputFiles, outputPath, format, extraArgs })),
	detectProject: (dirPath: string) => typedError<{
	project: ProjectMeta,
	outline?: OutlineConfig,
	writing?: WritingConfig,
} | null, string>(__TAURI_INVOKE("detect_project", { dirPath })),
	readProjectConfig: (dirPath: string) => typedError<ProjectConfig, string>(__TAURI_INVOKE("read_project_config", { dirPath })),
	getEffectiveSettings: (dirPath: string | null) => typedError<EffectiveSettings, string>(__TAURI_INVOKE("get_effective_settings", { dirPath })),
	getGlobalSettings: () => typedError<GlobalSettings, string>(__TAURI_INVOKE("get_global_settings")),
	writeGlobalSettings: (view: ViewConfig | null, newFile: NewFileConfig | null, plugins: PluginsConfig | null) => typedError<null, string>(__TAURI_INVOKE("write_global_settings", { view, newFile, plugins })),
	writeProjectSettings: (dirPath: string, view: ViewConfig | null, newFile: NewFileConfig | null, plugins: PluginsConfig | null) => typedError<null, string>(__TAURI_INVOKE("write_project_settings", { dirPath, view, newFile, plugins })),
	logStartupPhase: (name: string, sinceStartMs: number) => typedError<null, string>(__TAURI_INVOKE("log_startup_phase", { name, sinceStartMs })),
	startFileWatcher: (dirPath: string) => typedError<null, string>(__TAURI_INVOKE("start_file_watcher", { dirPath })),
	stopFileWatcher: () => typedError<null, string>(__TAURI_INVOKE("stop_file_watcher")),
	registerOpenFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("register_open_file", { path })),
	unregisterOpenFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("unregister_open_file", { path })),
	registerWriteIgnore: (path: string) => typedError<null, string>(__TAURI_INVOKE("register_write_ignore", { path })),
	getRecentProjects: () => typedError<RecentProject[], string>(__TAURI_INVOKE("get_recent_projects")),
	addRecentProject: (path: string, name: string) => typedError<null, string>(__TAURI_INVOKE("add_recent_project", { path, name })),
	removeRecentProject: (path: string) => typedError<null, string>(__TAURI_INVOKE("remove_recent_project", { path })),
	// Pin or unpin a single project. Pinned projects always sort above unpinned.
	setProjectPinned: (path: string, pinned: boolean) => typedError<null, string>(__TAURI_INVOKE("set_project_pinned", { path, pinned })),
	/**
	 *  Reorder recent projects by the given path list. Each path's index in
	 *  `ordered_paths` becomes its new `sort_order`. Paths not in the list keep
	 *  their existing `sort_order`.
	 */
	reorderRecentProjects: (orderedPaths: string[]) => typedError<null, string>(__TAURI_INVOKE("reorder_recent_projects", { orderedPaths })),
	// Scan ~/.novelist/plugins/ and return info for each plugin found.
	listPlugins: () => typedError<PluginInfo[], string>(__TAURI_INVOKE("list_plugins")),
	// Load and activate a plugin by its ID.
	loadPlugin: (pluginId: string) => typedError<null, string>(__TAURI_INVOKE("load_plugin", { pluginId })),
	// Unload (deactivate) a plugin.
	unloadPlugin: (pluginId: string) => typedError<null, string>(__TAURI_INVOKE("unload_plugin", { pluginId })),
	/**
	 *  Unload then re-load a plugin from disk. Used to pick up edits to
	 *  `manifest.toml` / `index.js` without restarting the app.
	 */
	reloadPlugin: (pluginId: string) => typedError<null, string>(__TAURI_INVOKE("reload_plugin", { pluginId })),
	// Get all commands registered by active plugins.
	getPluginCommands: () => typedError<RegisteredCommandInfo[], string>(__TAURI_INVOKE("get_plugin_commands")),
	// Execute a registered plugin command. Returns any text replacements the plugin wants to make.
	invokePluginCommand: (pluginId: string, commandId: string) => typedError<PluginReplacementResult[], string>(__TAURI_INVOKE("invoke_plugin_command", { pluginId, commandId })),
	// Update the document state that plugins can read.
	setPluginDocumentState: (content: string, selectionFrom: number, selectionTo: number, wordCount: number) => typedError<null, string>(__TAURI_INVOKE("set_plugin_document_state", { content, selectionFrom, selectionTo, wordCount })),
	/**
	 *  Enable or disable a plugin (persists to settings file).
	 *  When enabling, also loads the plugin. When disabling, unloads it.
	 */
	setPluginEnabled: (pluginId: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_plugin_enabled", { pluginId, enabled })),
	/**
	 *  Create a minimal plugin at ~/.novelist/plugins/<id>/ with manifest.toml + index.js.
	 *  ID must match `[a-z0-9][a-z0-9-]*`. display_name defaults to id.
	 */
	scaffoldPlugin: (id: string, displayName: string | null) => typedError<string, string>(__TAURI_INVOKE("scaffold_plugin", { id, displayName })),
	// Return the absolute path of ~/.novelist/plugins/, creating it if missing.
	getPluginsDir: () => typedError<string, string>(__TAURI_INVOKE("get_plugins_dir")),
	// Open a large file into a Rope. Returns metadata.
	ropeOpen: (path: string) => typedError<RopeDocumentMeta, string>(__TAURI_INVOKE("rope_open", { path })),
	/**
	 *  Get text for a range of lines. Lines are 0-indexed.
	 *  Returns the text and actual line range (clamped to document bounds).
	 */
	ropeGetLines: (fileId: string, startLine: number, endLine: number) => typedError<ViewportContent, string>(__TAURI_INVOKE("rope_get_lines", { fileId, startLine, endLine })),
	/**
	 *  Apply an edit to the Rope at character offsets.
	 *  `from` and `to` are character (not byte) offsets relative to the full document.
	 *  `insert` is the replacement text (empty string = deletion).
	 */
	ropeApplyEdit: (fileId: string, fromChar: number, toChar: number, insert: string) => typedError<number, string>(__TAURI_INVOKE("rope_apply_edit", { fileId, fromChar, toChar, insert })),
	// Save the Rope to disk atomically.
	ropeSave: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("rope_save", { fileId })),
	// Close a Rope document and release memory.
	ropeClose: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("rope_close", { fileId })),
	// Get the character offset for a given line number (0-indexed).
	ropeLineToChar: (fileId: string, line: number) => typedError<number, string>(__TAURI_INVOKE("rope_line_to_char", { fileId, line })),
	readDraftNote: (projectDir: string, filePath: string) => typedError<string | null, string>(__TAURI_INVOKE("read_draft_note", { projectDir, filePath })),
	writeDraftNote: (projectDir: string, filePath: string, content: string) => typedError<null, string>(__TAURI_INVOKE("write_draft_note", { projectDir, filePath, content })),
	deleteDraftNote: (projectDir: string, filePath: string) => typedError<null, string>(__TAURI_INVOKE("delete_draft_note", { projectDir, filePath })),
	hasDraftNote: (projectDir: string, filePath: string) => typedError<boolean, string>(__TAURI_INVOKE("has_draft_note", { projectDir, filePath })),
	searchInProject: (dirPath: string, query: string) => typedError<SearchMatch[], string>(__TAURI_INVOKE("search_in_project", { dirPath, query })),
	createSnapshot: (projectDir: string, name: string) => typedError<SnapshotMeta, string>(__TAURI_INVOKE("create_snapshot", { projectDir, name })),
	listSnapshots: (projectDir: string) => typedError<SnapshotMeta[], string>(__TAURI_INVOKE("list_snapshots", { projectDir })),
	restoreSnapshot: (projectDir: string, snapshotId: string) => typedError<null, string>(__TAURI_INVOKE("restore_snapshot", { projectDir, snapshotId })),
	deleteSnapshot: (projectDir: string, snapshotId: string) => typedError<null, string>(__TAURI_INVOKE("delete_snapshot", { projectDir, snapshotId })),
	recordWritingStats: (projectDir: string, wordDelta: number, minutes: number) => typedError<null, string>(__TAURI_INVOKE("record_writing_stats", { projectDir, wordDelta, minutes })),
	getWritingStats: (projectDir: string, chapters: ChapterStatsInput[]) => typedError<WritingStatsOverview, string>(__TAURI_INVOKE("get_writing_stats", { projectDir, chapters })),
	listTemplates: () => typedError<TemplateInfo[], string>(__TAURI_INVOKE("list_templates")),
	createProjectFromTemplate: (templateId: string, projectName: string, parentDir: string) => typedError<string, string>(__TAURI_INVOKE("create_project_from_template", { templateId, projectName, parentDir })),
	saveProjectAsTemplate: (projectDir: string, templateName: string) => typedError<TemplateInfo, string>(__TAURI_INVOKE("save_project_as_template", { projectDir, templateName })),
	deleteTemplate: (templateId: string) => typedError<null, string>(__TAURI_INVOKE("delete_template", { templateId })),
	importTemplateZip: (zipPath: string) => typedError<TemplateInfo, string>(__TAURI_INVOKE("import_template_zip", { zipPath })),
	getPendingOpenFiles: () => __TAURI_INVOKE<string[]>("get_pending_open_files"),
	/**
	 *  Read an image file and return it as a data URI (e.g. `data:image/png;base64,...`).
	 *  Used by the WYSIWYG editor to render local images without the asset protocol.
	 */
	readImageDataUri: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_image_data_uri", { path })),
	/**
	 *  Write raw bytes (passed as base64) to a file. Used by the frontend to save
	 *  pasted/dropped images without UTF-8 encoding corruption.
	 */
	writeBinaryFile: (path: string, base64Data: string) => typedError<null, string>(__TAURI_INVOKE("write_binary_file", { path, base64Data })),
	// Reveal a file or folder in the platform's file manager (Finder on macOS).
	revealInFileManager: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
	// Duplicate a file. Returns the path of the new copy.
	duplicateFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("duplicate_file", { path })),
	// Snippet-template commands (bundled + project-scoped .md files with YAML front-matter).
	listTemplateFiles: (projectDir: string | null) => typedError<TemplateFileSummary[], string>(__TAURI_INVOKE("list_template_files", { projectDir })),
	readTemplateFile: (source: TemplateSource, id: string, projectDir: string | null) => typedError<TemplateFile, string>(__TAURI_INVOKE("read_template_file", { source, id, projectDir })),
	writeTemplateFile: (projectDir: string, id: string, frontMatter: TemplateFrontMatterInput, body: string) => typedError<TemplateFileSummary, string>(__TAURI_INVOKE("write_template_file", { projectDir, id, frontMatter, body })),
	renameTemplateFile: (projectDir: string, oldId: string, newId: string) => typedError<TemplateFileSummary, string>(__TAURI_INVOKE("rename_template_file", { projectDir, oldId, newId })),
	deleteTemplateFile: (projectDir: string, id: string) => typedError<null, string>(__TAURI_INVOKE("delete_template_file", { projectDir, id })),
	duplicateBundledTemplate: (projectDir: string, bundledId: string, newId: string | null) => typedError<TemplateFileSummary, string>(__TAURI_INVOKE("duplicate_bundled_template", { projectDir, bundledId, newId })),
	createFileWithBody: (dir: string, filename: string, body: string) => typedError<string, string>(__TAURI_INVOKE("create_file_with_body", { dir, filename, body })),
	aiFetchStreamStart: (req: AiFetchRequest) => typedError<string, string>(__TAURI_INVOKE("ai_fetch_stream_start", { req })),
	aiFetchStreamCancel: (streamId: string) => typedError<null, string>(__TAURI_INVOKE("ai_fetch_stream_cancel", { streamId })),
	claudeCliDetect: () => __TAURI_INVOKE<{
	path: string,
	version: string | null,
} | null>("claude_cli_detect"),
	claudeCliSpawn: (req: ClaudeSpawnRequest) => typedError<string, string>(__TAURI_INVOKE("claude_cli_spawn", { req })),
	claudeCliSend: (sessionId: string, line: string) => typedError<null, string>(__TAURI_INVOKE("claude_cli_send", { sessionId, line })),
	claudeCliKill: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("claude_cli_kill", { sessionId })),
	getSyncConfig: (projectDir: string) => typedError<SyncConfigMasked, string>(__TAURI_INVOKE("get_sync_config", { projectDir })),
	saveSyncConfig: (projectDir: string, config: SyncConfig) => typedError<null, string>(__TAURI_INVOKE("save_sync_config", { projectDir, config })),
	syncNow: (projectDir: string) => typedError<SyncStatus, string>(__TAURI_INVOKE("sync_now", { projectDir })),
	testSyncConnection: (webdavUrl: string, username: string, password: string) => typedError<boolean, string>(__TAURI_INVOKE("test_sync_connection", { webdavUrl, username, password })),
};

/* Types */
export type AiFetchRequest = {
	/**
	 *  Full URL. Must be https:// (http:// allowed only for localhost for
	 *  self-hosted / ollama during development).
	 */
	url: string,
	headers: ([string, string])[],
	// Raw JSON body. The caller (plugin) owns the shape — we just POST it.
	body: string,
	/**
	 *  When true, parse the response as SSE (split on `\n\n`, strip `data: `,
	 *  skip `[DONE]`). When false, buffer the full body and emit one chunk.
	 */
	sse: boolean,
};

export type ChapterStats = {
	file_name: string,
	file_path: string,
	word_count: number,
};

export type ChapterStatsInput = {
	file_name: string,
	file_path: string,
	word_count: number,
};

export type ClaudeSpawnRequest = {
	// Override the auto-detected CLI path.
	cli_path: string | null,
	// Working directory for the spawned process. Default: inherit.
	cwd: string | null,
	system_prompt: string | null,
	// Extra `--add-dir` values (plugin usually includes the project root).
	add_dirs: string[],
	/**
	 *  One of: "acceptEdits", "auto", "bypassPermissions", "default",
	 *  "dontAsk", "plan". Passed through as-is.
	 */
	permission_mode: string | null,
	model: string | null,
	// Plugin-owned UUID; must be a valid UUID string on the CLI side.
	session_uuid: string,
	/**
	 *  Extra CLI args (escape hatch). Validated against a blocklist of
	 *  flags we manage ourselves.
	 */
	extra_args: string[],
};

export type DailyStats = {
	date: string,
	words_written: number,
	time_minutes: number,
};

export type DetectedCli = {
	path: string,
	version: string | null,
};

export type FileEntry = {
	name: string,
	path: string,
	is_dir: boolean,
	size: number,
	// Unix epoch milliseconds; None when filesystem doesn't expose mtime.
	mtime: number | null,
};

export type OutlineConfig = {
	order?: string[],
};

export type PandocStatus = {
	available: boolean,
	version: string | null,
};

export type PluginInfo = {
	id: string,
	name: string,
	version: string,
	permissions: string[],
	active: boolean,
	ui: PluginUiConfig | null,
	description: string | null,
	author: string | null,
	icon: string | null,
	builtin: boolean,
	enabled: boolean,
};

export type PluginReplacementResult = {
	from: number,
	to: number,
	text: string,
};

export type PluginUiConfig = {
	type: string,
	entry: string,
	width?: number | null,
	label?: string | null,
	file_extensions?: string[] | null,
};

export type ProjectConfig = {
	project: ProjectMeta,
	outline?: OutlineConfig,
	writing?: WritingConfig,
	view?: ViewConfig,
	new_file?: NewFileConfig,
	plugins?: PluginsConfig,
};

export type ViewConfig = {
	sort_mode?: string | null,
	show_hidden_files?: boolean | null,
};

export type NewFileConfig = {
	template?: string | null,
	detect_from_folder?: boolean | null,
	auto_rename_from_h1?: boolean | null,
	default_dir?: string | null,
	last_used_dir?: string | null,
};

export type PluginsConfig = {
	enabled: { [key: string]: boolean },
};

export type GlobalSettings = {
	view?: ViewConfig,
	new_file?: NewFileConfig,
	plugins?: PluginsConfig,
};

export type ResolvedView = {
	sort_mode: string,
	show_hidden_files: boolean,
};

export type ResolvedNewFile = {
	template: string,
	detect_from_folder: boolean,
	auto_rename_from_h1: boolean,
	default_dir: string | null,
	last_used_dir: string | null,
};

export type ResolvedPlugins = {
	enabled: { [key: string]: boolean },
};

export type EffectiveSettings = {
	view: ResolvedView,
	new_file: ResolvedNewFile,
	plugins: ResolvedPlugins,
	is_project_scoped: boolean,
};

export type ProjectMeta = {
	name: string,
	type?: string,
	version?: string,
};

export type RecentProject = {
	path: string,
	name: string,
	last_opened: string,
	/**
	 *  `true` keeps the project above all unpinned ones. Optional in the
	 *  persisted JSON so pre-existing files deserialize cleanly.
	 */
	pinned?: boolean,
	/**
	 *  Manual rank within the pinned / unpinned group. Smaller = earlier.
	 *  `None` falls back to `last_opened` order. Optional for back-compat.
	 */
	sort_order?: number | null,
};

export type RegisteredCommandInfo = {
	plugin_id: string,
	command_id: string,
	label: string,
};

export type RopeDocumentMeta = {
	file_id: string,
	total_lines: number,
	total_bytes: number,
};

export type SearchMatch = {
	file_path: string,
	file_name: string,
	line_number: number,
	line_text: string,
	match_start: number,
	match_end: number,
};

export type SnapshotMeta = {
	id: string,
	name: string,
	timestamp: number,
	file_count: number,
	total_bytes: number,
};

export type SyncConfig = {
	enabled: boolean,
	webdav_url: string,
	username: string,
	password: string,
	interval_minutes: number,
};

export type SyncConfigMasked = {
	enabled: boolean,
	webdav_url: string,
	username: string,
	password: string,
	interval_minutes: number,
};

export type SyncStatus = {
	last_sync: string | null,
	files_uploaded: number,
	files_downloaded: number,
	errors: string[],
	in_progress: boolean,
};

// Info returned to the frontend for listing templates.
export type TemplateInfo = {
	id: string,
	name: string,
	description: string,
	category: string,
	// Whether this is a built-in template (cannot be deleted).
	builtin: boolean,
};

export type TemplateSource = "bundled" | "project";
export type TemplateMode = "insert" | "new-file";

export type TemplateFileSummary = {
	id: string,
	source: TemplateSource,
	name: string,
	mode: TemplateMode,
	description: string | null,
	defaultFilename: string | null,
};

export type TemplateFile = {
	summary: TemplateFileSummary,
	body: string,
};

export type TemplateFrontMatterInput = {
	name: string,
	mode: TemplateMode,
	description: string | null,
	defaultFilename: string | null,
};

export type ViewportContent = {
	// The text content for the requested line range
	text: string,
	// Actual start line (0-indexed)
	start_line: number,
	// Actual end line (exclusive, 0-indexed)
	end_line: number,
	// Total lines in document (can change after edits)
	total_lines: number,
};

export type WritingConfig = {
	daily_goal?: number,
	auto_save_minutes?: number,
};

export type WritingStatsOverview = {
	daily: DailyStats[],
	total_words: number,
	chapters: ChapterStats[],
	streak_days: number,
	today_words: number,
	today_minutes: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

