// @ts-nocheck
// Auto-generated by tauri-specta

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	readFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_file", { path })),
	writeFile: (path: string, content: string) => typedError<null, string>(__TAURI_INVOKE("write_file", { path, content })),
	writeFileIfUnchanged: (projectDir: string, path: string, expectedContent: string | null, content: string) => typedError<WriteFileIfUnchangedResult, string>(__TAURI_INVOKE("write_file_if_unchanged", { projectDir, path, expectedContent, content })),
	/**
	 *  Returns the detected encoding for a file that was previously read via `read_file`.
	 *  Returns `"UTF-8"` if the file is UTF-8 (or was never read).
	 */
	getFileEncoding: (path: string) => typedError<string, string>(__TAURI_INVOKE("get_file_encoding", { path })),
	listDirectory: (path: string, showHidden: boolean | null) => typedError<FileEntry[], string>(__TAURI_INVOKE("list_directory", { path, showHidden })),
	createFile: (parentDir: string, filename: string) => typedError<string, string>(__TAURI_INVOKE("create_file", { parentDir, filename })),
	/**
	 *  Create a scratch file in ~/.cache/novelist/ for single-file mode.
	 *  Filename pattern: `novelist_scratch_<unix_millis>.md`
	 *  This pattern is checked by the frontend to detect unsaved scratch files.
	 *  Returns the absolute path of the created file.
	 */
	createScratchFile: () => typedError<string, string>(__TAURI_INVOKE("create_scratch_file")),
	createDirectory: (parentDir: string, name: string) => typedError<string, string>(__TAURI_INVOKE("create_directory", { parentDir, name })),
	/**
	 *  Rename a file or folder in place.
	 *  When `allow_collision_bump` is Some(true), appends " 2", " 3", … on collision.
	 *  Defaults to error-on-collision when None or Some(false).
	 */
	renameItem: (projectDir: string, oldPath: string, newName: string, allowCollisionBump: boolean | null) => typedError<RenameItemResult, string>(__TAURI_INVOKE("rename_item", { projectDir, oldPath, newName, allowCollisionBump })),
	computeDocumentKey: (projectDir: string, filePath: string) => typedError<string, string>(__TAURI_INVOKE("compute_document_key", { projectDir, filePath })),
	readManagedNameState: (projectDir: string, filePath: string) => typedError<{
	version: number,
	status: ManagedNameStatus,
	templateRaw: string,
	currentH1: string,
	documentKey: string,
} | null, string>(__TAURI_INVOKE("read_managed_name_state", { projectDir, filePath })),
	writeManagedNameState: (projectDir: string, filePath: string, state: ManagedNameStateV1) => typedError<null, string>(__TAURI_INVOKE("write_managed_name_state", { projectDir, filePath, state })),
	deleteManagedNameState: (projectDir: string, filePath: string) => typedError<null, string>(__TAURI_INVOKE("delete_managed_name_state", { projectDir, filePath })),
	/**  Emit a global Tauri event so other windows can update their tab state. */
	broadcastFileRenamed: (oldPath: string, newPath: string) => typedError<null, string>(__TAURI_INVOKE("broadcast_file_renamed", { oldPath, newPath })),
	/**
	 *  Move a file or folder into `target_dir`. Auto-numbers on collision
	 *  ("a.md" -> "a 2.md"). Rejects moving a folder into its own descendant.
	 */
	moveItem: (projectDir: string, sourcePath: string, targetDir: string) => typedError<RenameItemResult, string>(__TAURI_INVOKE("move_item", { projectDir, sourcePath, targetDir })),
	deleteItem: (path: string) => typedError<null, string>(__TAURI_INVOKE("delete_item", { path })),
	checkPandoc: () => typedError<PandocStatus_Serialize, string>(__TAURI_INVOKE("check_pandoc")),
	/**
	 *  Persist the user's pandoc binary override. `None` clears it (revert
	 *  to auto-detection). Empty string is treated as `None`.
	 */
	setPandocPath: (path: string | null) => typedError<null, string>(__TAURI_INVOKE("set_pandoc_path", { path })),
	stageExportCss: (requestId: string, css: string) => typedError<string, string>(__TAURI_INVOKE("stage_export_css", { requestId, css })),
	cancelExportProject: (requestId: string) => typedError<boolean, string>(__TAURI_INVOKE("cancel_export_project", { requestId })),
	exportProject: (inputFiles: string[], outputPath: string, format: string, extraArgs: string[], requestId: string | null, projectDir: string | null) => typedError<ExportProjectResult_Serialize, string>(__TAURI_INVOKE("export_project", { inputFiles, outputPath, format, extraArgs, requestId, projectDir })),
	detectProject: (dirPath: string) => typedError<{
	project: ProjectMeta,
	outline: OutlineConfig,
	writing: WritingConfig,
	/**  Sidebar/file-tree view preferences. Overrides global `~/.novelist/settings.json`. */
	view?: ViewConfig_Serialize,
	/**  New-file template preferences. Overrides global. */
	new_file?: NewFileConfig_Serialize,
	/**  Per-plugin enable flags (deltas from the global default map). */
	plugins?: PluginsConfig,
	/**
	 *  Per-project override for which image host is active. Credentials
	 *  stay in global settings — only the pointer to a configured host
	 *  can be overridden here.
	 */
	active_image_host_id?: string | null,
} | null, string>(__TAURI_INVOKE("detect_project", { dirPath })),
	readProjectConfig: (dirPath: string) => typedError<ProjectConfig_Serialize, string>(__TAURI_INVOKE("read_project_config", { dirPath })),
	/**
	 *  Return effective settings, merging global defaults with an optional
	 *  project overlay. `dir_path = None` returns global-only (scratch mode).
	 */
	getEffectiveSettings: (dirPath: string | null) => typedError<EffectiveSettings, string>(__TAURI_INVOKE("get_effective_settings", { dirPath })),
	/**
	 *  Return raw global defaults from `~/.novelist/settings.json` without
	 *  merging in any project overlay. Used by the frontend to compute plugin
	 *  delta overrides (only entries differing from global are persisted).
	 */
	getGlobalSettings: () => typedError<GlobalSettings_Serialize, string>(__TAURI_INVOKE("get_global_settings")),
	/**
	 *  Patch the global `~/.novelist/settings.json`. Only the `Some(..)` sections
	 *  are replaced; unspecified sections keep their current value on disk.
	 */
	writeGlobalSettings: (view: {
	sort_mode?: string | null,
	show_hidden_files?: boolean | null,
	wrap_file_names?: boolean | null,
	sidebar_font_size?: number | null,
} | null, newFile: {
	template?: string | null,
	detect_from_folder?: boolean | null,
	auto_rename_from_h1?: boolean | null,
	/**
	 *  User-pinned default location for new files. Absolute path. When set,
	 *  Cmd+N always creates here regardless of the recent activity pointer.
	 *  `None` means "follow the last-used tracker."
	 */
	default_dir?: string | null,
	/**
	 *  Live pointer: directory of the most recently created file. Updated
	 *  after every successful create (header button, Cmd+N, per-folder
	 *  context menu). Seeded to the project root on first open.
	 */
	last_used_dir?: string | null,
} | null, plugins: {
	enabled?: { [key in string]: boolean },
} | null) => typedError<null, string>(__TAURI_INVOKE("write_global_settings", { view, newFile, plugins })),
	/**
	 *  Patch `<dir>/.novelist/project.toml`. Only the provided sections are replaced.
	 *  Requires that a `project.toml` already exists (i.e. `dir` is a Novelist project).
	 */
	writeProjectSettings: (dirPath: string, view: {
	sort_mode?: string | null,
	show_hidden_files?: boolean | null,
	wrap_file_names?: boolean | null,
	sidebar_font_size?: number | null,
} | null, newFile: {
	template?: string | null,
	detect_from_folder?: boolean | null,
	auto_rename_from_h1?: boolean | null,
	/**
	 *  User-pinned default location for new files. Absolute path. When set,
	 *  Cmd+N always creates here regardless of the recent activity pointer.
	 *  `None` means "follow the last-used tracker."
	 */
	default_dir?: string | null,
	/**
	 *  Live pointer: directory of the most recently created file. Updated
	 *  after every successful create (header button, Cmd+N, per-folder
	 *  context menu). Seeded to the project root on first open.
	 */
	last_used_dir?: string | null,
} | null, plugins: {
	enabled?: { [key in string]: boolean },
} | null) => typedError<null, string>(__TAURI_INVOKE("write_project_settings", { dirPath, view, newFile, plugins })),
	startFileWatcher: (dirPath: string) => typedError<null, string>(__TAURI_INVOKE("start_file_watcher", { dirPath })),
	stopFileWatcher: () => typedError<null, string>(__TAURI_INVOKE("stop_file_watcher")),
	registerOpenFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("register_open_file", { path })),
	unregisterOpenFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("unregister_open_file", { path })),
	registerWriteIgnore: (path: string) => typedError<null, string>(__TAURI_INVOKE("register_write_ignore", { path })),
	/**
	 *  Polling fallback for external-edit detection.
	 *
	 *  The notify watcher only covers a single recursively-watched project dir, so
	 *  it misses files opened in single-file mode (no project → no watcher) and can
	 *  miss events on symlinked roots or when the OS coalesces/drops FSEvents. This
	 *  command re-checks every *tracked open file* directly and returns the paths
	 *  whose content changed on disk, so the frontend can reload them on a short
	 *  interval regardless of watcher coverage.
	 *
	 *  Cheap by design: an mtime stat gates the blake3 hash, so unchanged files
	 *  cost one `stat` each. Self-writes are suppressed only when the observed hash
	 *  equals the exact encoded hash registered by the Rust write path.
	 */
	pollExternalChanges: () => typedError<ExternalFileChangePayload[], string>(__TAURI_INVOKE("poll_external_changes")),
	getRecentProjects: () => typedError<RecentProject[], string>(__TAURI_INVOKE("get_recent_projects")),
	addRecentProject: (path: string, name: string) => typedError<null, string>(__TAURI_INVOKE("add_recent_project", { path, name })),
	removeRecentProject: (path: string) => typedError<null, string>(__TAURI_INVOKE("remove_recent_project", { path })),
	/**  Pin or unpin a single project. Pinned projects always sort above unpinned. */
	setProjectPinned: (path: string, pinned: boolean) => typedError<null, string>(__TAURI_INVOKE("set_project_pinned", { path, pinned })),
	/**
	 *  Reorder recent projects by the given path list. Each path's index in
	 *  `ordered_paths` becomes its new `sort_order`. Paths not in the list keep
	 *  their existing `sort_order`.
	 */
	reorderRecentProjects: (orderedPaths: string[]) => typedError<null, string>(__TAURI_INVOKE("reorder_recent_projects", { orderedPaths })),
	/**  Scan ~/.novelist/plugins/ and return info for each plugin found. */
	listPlugins: () => typedError<PluginInfo[], string>(__TAURI_INVOKE("list_plugins")),
	/**  Load and activate a plugin by its ID. */
	loadPlugin: (pluginId: string) => typedError<null, string>(__TAURI_INVOKE("load_plugin", { pluginId })),
	/**  Unload (deactivate) a plugin. */
	unloadPlugin: (pluginId: string) => typedError<null, string>(__TAURI_INVOKE("unload_plugin", { pluginId })),
	/**
	 *  Unload then re-load a plugin from disk. Used to pick up edits to
	 *  `manifest.toml` / `index.js` without restarting the app.
	 */
	reloadPlugin: (pluginId: string) => typedError<null, string>(__TAURI_INVOKE("reload_plugin", { pluginId })),
	/**  Get all commands registered by active plugins. */
	getPluginCommands: () => typedError<RegisteredCommandInfo[], string>(__TAURI_INVOKE("get_plugin_commands")),
	/**  Execute a registered plugin command. Returns any text replacements the plugin wants to make. */
	invokePluginCommand: (pluginId: string, commandId: string) => typedError<PluginReplacementResult[], string>(__TAURI_INVOKE("invoke_plugin_command", { pluginId, commandId })),
	/**  Update the document state that plugins can read. */
	setPluginDocumentState: (content: string, selectionFrom: number, selectionTo: number, wordCount: number) => typedError<null, string>(__TAURI_INVOKE("set_plugin_document_state", { content, selectionFrom, selectionTo, wordCount })),
	/**
	 *  Enable or disable a plugin (persists to settings file).
	 *  When enabling, also loads the plugin. When disabling, unloads it.
	 */
	setPluginEnabled: (pluginId: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_plugin_enabled", { pluginId, enabled })),
	/**
	 *  Create a minimal plugin at ~/.novelist/plugins/<id>/ with manifest.toml + index.js.
	 *  ID must match `[a-z0-9][a-z0-9-]*`. display_name defaults to id.
	 */
	scaffoldPlugin: (id: string, displayName: string | null) => typedError<string, string>(__TAURI_INVOKE("scaffold_plugin", { id, displayName })),
	/**  Return the absolute path of ~/.novelist/plugins/, creating it if missing. */
	getPluginsDir: () => typedError<string, string>(__TAURI_INVOKE("get_plugins_dir")),
	isPortableMode: () => __TAURI_INVOKE<PortableModeInfo>("is_portable_mode"),
	/**  Open a large file into a Rope. Returns metadata. */
	ropeOpen: (path: string) => typedError<RopeDocumentMeta, string>(__TAURI_INVOKE("rope_open", { path })),
	/**
	 *  Get text for a range of lines. Lines are 0-indexed.
	 *  Returns the text and actual line range (clamped to document bounds).
	 */
	ropeGetLines: (fileId: string, startLine: number, endLine: number) => typedError<ViewportContent, string>(__TAURI_INVOKE("rope_get_lines", { fileId, startLine, endLine })),
	/**
	 *  Apply an edit to the Rope at character offsets.
	 *  `from` and `to` are character (not byte) offsets relative to the full document.
	 *  `insert` is the replacement text (empty string = deletion).
	 */
	ropeApplyEdit: (fileId: string, fromChar: number, toChar: number, insert: string) => typedError<number, string>(__TAURI_INVOKE("rope_apply_edit", { fileId, fromChar, toChar, insert })),
	/**  Save the Rope to disk atomically. */
	ropeSave: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("rope_save", { fileId })),
	/**  Close a Rope document and release memory. */
	ropeClose: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("rope_close", { fileId })),
	/**  Get the character offset for a given line number (0-indexed). */
	ropeLineToChar: (fileId: string, line: number) => typedError<number, string>(__TAURI_INVOKE("rope_line_to_char", { fileId, line })),
	ropeSnapshot: (fileId: string) => typedError<RopeSnapshot, string>(__TAURI_INVOKE("rope_snapshot", { fileId })),
	readDraftNote: (projectDir: string, filePath: string) => typedError<string | null, string>(__TAURI_INVOKE("read_draft_note", { projectDir, filePath })),
	writeDraftNote: (projectDir: string, filePath: string, content: string) => typedError<null, string>(__TAURI_INVOKE("write_draft_note", { projectDir, filePath, content })),
	deleteDraftNote: (projectDir: string, filePath: string) => typedError<null, string>(__TAURI_INVOKE("delete_draft_note", { projectDir, filePath })),
	hasDraftNote: (projectDir: string, filePath: string) => typedError<boolean, string>(__TAURI_INVOKE("has_draft_note", { projectDir, filePath })),
	searchInProject: (dirPath: string, query: string) => typedError<SearchMatch[], string>(__TAURI_INVOKE("search_in_project", { dirPath, query })),
	createSnapshot: (projectDir: string, name: string) => typedError<SnapshotMeta, string>(__TAURI_INVOKE("create_snapshot", { projectDir, name })),
	listSnapshots: (projectDir: string) => typedError<SnapshotMeta[], string>(__TAURI_INVOKE("list_snapshots", { projectDir })),
	restoreSnapshot: (projectDir: string, snapshotId: string) => typedError<null, string>(__TAURI_INVOKE("restore_snapshot", { projectDir, snapshotId })),
	deleteSnapshot: (projectDir: string, snapshotId: string) => typedError<null, string>(__TAURI_INVOKE("delete_snapshot", { projectDir, snapshotId })),
	recordWritingStats: (projectDir: string, wordDelta: number, minutes: number) => typedError<null, string>(__TAURI_INVOKE("record_writing_stats", { projectDir, wordDelta, minutes })),
	getWritingStats: (projectDir: string) => typedError<WritingStatsOverview, string>(__TAURI_INVOKE("get_writing_stats", { projectDir })),
	listTemplates: () => typedError<TemplateInfo[], string>(__TAURI_INVOKE("list_templates")),
	createProjectFromTemplate: (templateId: string, projectName: string, parentDir: string, locale: string) => typedError<string, string>(__TAURI_INVOKE("create_project_from_template", { templateId, projectName, parentDir, locale })),
	inspectLiterarySource: (path: string) => typedError<LiterarySourceInspection, string>(__TAURI_INVOKE("inspect_literary_source", { path })),
	createLiteraryStudyProject: (request: CreateLiteraryStudyProjectRequest) => typedError<CreateLiteraryStudyProjectResult, string>(__TAURI_INVOKE("create_literary_study_project", { request })),
	saveProjectAsTemplate: (projectDir: string, templateName: string) => typedError<TemplateInfo, string>(__TAURI_INVOKE("save_project_as_template", { projectDir, templateName })),
	deleteTemplate: (templateId: string) => typedError<null, string>(__TAURI_INVOKE("delete_template", { templateId })),
	importTemplateZip: (zipPath: string) => typedError<TemplateInfo, string>(__TAURI_INVOKE("import_template_zip", { zipPath })),
	listTemplateFiles: (projectDir: string | null) => typedError<TemplateFileSummary[], string>(__TAURI_INVOKE("list_template_files", { projectDir })),
	readTemplateFile: (source: TemplateSource, id: string, projectDir: string | null) => typedError<TemplateFile, string>(__TAURI_INVOKE("read_template_file", { source, id, projectDir })),
	writeTemplateFile: (projectDir: string, id: string, frontMatter: TemplateFrontMatterInput, body: string) => typedError<TemplateFileSummary, string>(__TAURI_INVOKE("write_template_file", { projectDir, id, frontMatter, body })),
	renameTemplateFile: (projectDir: string, oldId: string, newId: string) => typedError<TemplateFileSummary, string>(__TAURI_INVOKE("rename_template_file", { projectDir, oldId, newId })),
	deleteTemplateFile: (projectDir: string, id: string) => typedError<null, string>(__TAURI_INVOKE("delete_template_file", { projectDir, id })),
	duplicateBundledTemplate: (projectDir: string, bundledId: string, newId: string | null) => typedError<TemplateFileSummary, string>(__TAURI_INVOKE("duplicate_bundled_template", { projectDir, bundledId, newId })),
	/**
	 *  Create a new file in `dir` with `body`. If `filename` already exists,
	 *  auto-bump `stem 2.ext`, `stem 3.ext`, … just like the existing file-tree
	 *  "New file" flow. Returns the resolved absolute path. Used by new-file-mode
	 *  template execution so the frontend does not need to orchestrate sanitize +
	 *  bump + write itself.
	 */
	createFileWithBody: (dir: string, filename: string, body: string) => typedError<string, string>(__TAURI_INVOKE("create_file_with_body", { dir, filename, body })),
	getPendingOpenFiles: () => __TAURI_INVOKE<PendingFile[]>("get_pending_open_files"),
	getPendingOpenProjects: () => __TAURI_INVOKE<string[]>("get_pending_open_projects"),
	/**  Tauri command — FE wrapper around `route_single_file_open`. */
	routeSingleFileOpenCmd: (sourceLabel: string | null, path: string, line: number | null, col: number | null, forceNew: boolean) => __TAURI_INVOKE<RouteResult>("route_single_file_open_cmd", { sourceLabel, path, line, col, forceNew }),
	/**
	 *  Tauri command — each window reports its bid in response to a
	 *  `file-open-bid-request` event.
	 */
	submitFileOpenBid: (bidId: number, windowLabel: string, canClaim: boolean, hasProject: boolean) => typedError<null, string>(__TAURI_INVOKE("submit_file_open_bid", { bidId, windowLabel, canClaim, hasProject })),
	cliShimStatus: () => typedError<CliShimStatus, string>(__TAURI_INVOKE("cli_shim_status")),
	installCliShim: () => typedError<CliShimStatus, string>(__TAURI_INVOKE("install_cli_shim")),
	/**
	 *  Read a Markdown image through a project/document capability. `reference`
	 *  remains relative to `base_dir`; both are confined under `allowed_root`.
	 *  Every path component is opened relative to retained directory handles, and
	 *  symlinks are rejected before any image bytes are read.
	 */
	readImageBytes: (baseDir: string, reference: string) => typedError<number[], string>(__TAURI_INVOKE("read_image_bytes", { baseDir, reference })),
	uploadImageQiniu: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_qiniu", { bytes, filename, mime, config })),
	uploadImageAliyunOss: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_aliyun_oss", { bytes, filename, mime, config })),
	uploadImageS3: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_s3", { bytes, filename, mime, config })),
	uploadImageImgur: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_imgur", { bytes, filename, mime, config })),
	uploadImageSmms: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_smms", { bytes, filename, mime, config })),
	uploadImageCustom: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_custom", { bytes, filename, mime, config })),
	/**  Read the global `image_hosts` settings block. */
	getImageHostSettings: () => typedError<ImageHostSettings_Serialize, string>(__TAURI_INVOKE("get_image_host_settings")),
	/**  Replace the global `image_hosts` settings block atomically. */
	setImageHostSettings: (settings: ImageHostSettings_Deserialize) => typedError<null, string>(__TAURI_INVOKE("set_image_host_settings", { settings })),
	publishToGhost: (input: PublishInput_Deserialize, config: PlatformConfig) => typedError<PublishResult_Serialize, string>(__TAURI_INVOKE("publish_to_ghost", { input, config })),
	publishToWordpressSelfHosted: (input: PublishInput_Deserialize, config: PlatformConfig) => typedError<PublishResult_Serialize, string>(__TAURI_INVOKE("publish_to_wordpress_self_hosted", { input, config })),
	publishToWordpressCom: (input: PublishInput_Deserialize, config: PlatformConfig) => typedError<PublishResult_Serialize, string>(__TAURI_INVOKE("publish_to_wordpress_com", { input, config })),
	publishToMedium: (input: PublishInput_Deserialize, config: PlatformConfig) => typedError<PublishResult_Serialize, string>(__TAURI_INVOKE("publish_to_medium", { input, config })),
	verifyWordpressSelfHostedUpdate: (updateTarget: UpdateTarget_Deserialize, config: PlatformConfig) => typedError<null, string>(__TAURI_INVOKE("verify_wordpress_self_hosted_update", { updateTarget, config })),
	verifyWordpressComUpdate: (updateTarget: UpdateTarget_Deserialize, config: PlatformConfig) => typedError<null, string>(__TAURI_INVOKE("verify_wordpress_com_update", { updateTarget, config })),
	uploadPostImageGhost: (bytes: number[], filename: string, mime: string, config: PlatformConfig) => typedError<PostImageUploadResult, string>(__TAURI_INVOKE("upload_post_image_ghost", { bytes, filename, mime, config })),
	uploadPostImageWordpressSelfHosted: (bytes: number[], filename: string, mime: string, config: PlatformConfig) => typedError<PostImageUploadResult, string>(__TAURI_INVOKE("upload_post_image_wordpress_self_hosted", { bytes, filename, mime, config })),
	uploadPostImageWordpressCom: (bytes: number[], filename: string, mime: string, config: PlatformConfig) => typedError<PostImageUploadResult, string>(__TAURI_INVOKE("upload_post_image_wordpress_com", { bytes, filename, mime, config })),
	uploadPostImageMedium: (bytes: number[], filename: string, mime: string, config: PlatformConfig) => typedError<PostImageUploadResult, string>(__TAURI_INVOKE("upload_post_image_medium", { bytes, filename, mime, config })),
	/**
	 *  Convert Markdown to HTML via the user-configured or discovered system Pandoc binary.
	 *  Used by the frontend orchestrator before submitting to Ghost / WP /
	 *  WP.com (Medium consumes Markdown directly).
	 */
	convertMarkdownToHtml: (markdown: string) => typedError<string, string>(__TAURI_INVOKE("convert_markdown_to_html", { markdown })),
	convertMarkdownToStyledHtml: (markdown: string) => typedError<string, string>(__TAURI_INVOKE("convert_markdown_to_styled_html", { markdown })),
	readStyledCopyImage: (path: string, allowedRoots: string[]) => typedError<StyledCopyImage, string>(__TAURI_INVOKE("read_styled_copy_image", { path, allowedRoots })),
	writeStyledClipboard: (html: string, plainText: string) => typedError<null, string>(__TAURI_INVOKE("write_styled_clipboard", { html, plainText })),
	/**
	 *  Read-only credentials check per platform. Returns a short
	 *  human-friendly status line like "Connected as alice" on success;
	 *  errors propagate with the platform's response body included.
	 */
	verifyPublishChannel: (config: PlatformConfig) => typedError<string, string>(__TAURI_INVOKE("verify_publish_channel", { config })),
	/**
	 *  Fetch existing tag names for the channel (used by the Publish
	 *  dialog's tag autocomplete). Returns an empty vec for platforms
	 *  that don't expose a tag-list API in v0.2.4 (Medium, WordPress —
	 *  can be added later by extending the relevant adapter).
	 */
	listPublishTags: (config: PlatformConfig) => typedError<string[], string>(__TAURI_INVOKE("list_publish_tags", { config })),
	readClipboardImage: () => typedError<ClipboardImage, string>(__TAURI_INVOKE("read_clipboard_image")),
	getPublishSettings: () => typedError<PublishSettings, string>(__TAURI_INVOKE("get_publish_settings")),
	setPublishSettings: (settings: PublishSettings) => typedError<null, string>(__TAURI_INVOKE("set_publish_settings", { settings })),
	/**
	 *  Task 14: read the persisted per-channel Publish form drafts for one
	 *  document. Returns an empty snapshot when the sidecar does not yet
	 *  exist. Malformed top-level JSON surfaces as `AppError::Json`;
	 *  per-channel parse errors are surfaced in `invalidChannelIds` so a
	 *  broken entry cannot hide sibling channels.
	 */
	readPublishFormDrafts: (projectDir: string, filePath: string) => typedError<PublishFormDraftsSnapshot_Serialize, string>(__TAURI_INVOKE("read_publish_form_drafts", { projectDir, filePath })),
	/**
	 *  Read only the durable remote identity for one document/channel.
	 *  Credentials and sibling channel state never cross this boundary.
	 */
	readPublishRemoteState: (projectDir: string, filePath: string, channelId: string) => typedError<{
	post_id: string,
	url?: string | null,
	revision?: string | null,
	provider_revision?: ProviderRevision_Serialize | null,
	capability?: BindingCapability | null,
} | null, string>(__TAURI_INVOKE("read_publish_remote_state", { projectDir, filePath, channelId })),
	/**
	 *  Task 14: persist one channel's Publish form draft while preserving
	 *  that channel's `remote` identity and `cover` reference. Uses the
	 *  Task 3 atomic sidecar update helper so writes are safe under
	 *  concurrent renames/publishes.
	 */
	writePublishFormDraft: (projectDir: string, filePath: string, channelId: string, form: FormDraft_Deserialize) => typedError<null, string>(__TAURI_INVOKE("write_publish_form_draft", { projectDir, filePath, channelId, form })),
	/**
	 *  Atomically persist a successful create/update result. Provider capability
	 *  is derived from Rust-owned channel settings, never trusted from the UI.
	 */
	persistPublishResult: (projectDir: string, filePath: string, channelId: string, result: PublishResult_Deserialize) => typedError<RemoteIdentity_Serialize, string>(__TAURI_INVOKE("persist_publish_result", { projectDir, filePath, channelId, result })),
	/**
	 *  Persist one channel's cover transactionally: validate and store the
	 *  content-addressed asset, atomically update only `ChannelState.cover`, then
	 *  run reference-safe cleanup. Form fields, remote identity, and siblings are
	 *  preserved by `update_publish_sidecar`.
	 */
	storePublishCover: (projectDir: string, filePath: string, channelId: string, bytes: number[], declaredMime: string) => typedError<PublishCoverAsset, string>(__TAURI_INVOKE("store_publish_cover", { projectDir, filePath, channelId, bytes, declaredMime })),
	/**
	 *  Restore the validated cover payload for one document/channel. A channel
	 *  without a cover returns `None`; a sidecar reference whose asset is missing
	 *  is an integrity error rather than a blank successful preview.
	 */
	loadPublishCover: (projectDir: string, filePath: string, channelId: string) => typedError<{
	cover: CoverRef,
	bytes: number[],
	filename: string,
	mime: string,
} | null, string>(__TAURI_INVOKE("load_publish_cover", { projectDir, filePath, channelId })),
	/**
	 *  Clear only the target channel's cover and then prune assets that no
	 *  sidecar references. Missing sidecars/channels/covers are idempotent.
	 */
	clearPublishCover: (projectDir: string, filePath: string, channelId: string) => typedError<null, string>(__TAURI_INVOKE("clear_publish_cover", { projectDir, filePath, channelId })),
	/**
	 *  Task 20: bind an existing remote post to a local document + channel
	 *  after authenticated verification.
	 *
	 *  Contract:
	 *  - The frontend supplies `project_dir`, `file_path`, `channel_id`,
	 *    and one `url_or_id` string. Credentials are NEVER passed in;
	 *    they are looked up on the Rust side by channel id from persisted
	 *    global settings.
	 *  - Verification is provider-specific: Ghost + both WordPress variants
	 *    authenticate-GET the referenced post and return an [`Updatable`]
	 *    [`VerifiedBinding`]. Medium returns a typed unsupported/insufficient-
	 *    scope error because its Integration Token API does not expose an
	 *    authenticated post-read/ownership endpoint. A successful `/v1/me`
	 *    token check alone is never treated as verified post identity.
	 *  - Sidecar mutation is atomic and touches ONLY the target channel's
	 *    `remote` field: `form`, `cover`, and every sibling channel are
	 *    preserved byte-identical.
	 *  - Any verification failure returns `AppError::Custom` with a typed
	 *    `PublishError` message. Sidecar bytes are unchanged on any failure.
	 *
	 *  [`Updatable`]: crate::services::publish::binding::BindingCapability::Updatable
	 *  [`UnsupportedUpdate`]: crate::services::publish::binding::BindingCapability::UnsupportedUpdate
	 */
	bindLegacyPublication: (projectDir: string, filePath: string, channelId: string, urlOrId: string) => typedError<VerifiedBinding_Serialize, string>(__TAURI_INVOKE("bind_legacy_publication", { projectDir, filePath, channelId, urlOrId })),
	/**
	 *  Write raw bytes (passed as base64) to a file. Used by the frontend to save
	 *  pasted/dropped images without UTF-8 encoding corruption.
	 */
	writeBinaryFile: (path: string, base64Data: string) => typedError<null, string>(__TAURI_INVOKE("write_binary_file", { path, base64Data })),
	/**  Reveal a file or folder in the platform's file manager (Finder on macOS). */
	revealInFileManager: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
	/**  Duplicate a file. Returns the path of the new copy. */
	duplicateFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("duplicate_file", { path })),
	/**
	 *  Record a frontend startup phase in the backend tracing log.
	 *  `since_start_ms` is the frontend-observed time relative to the first mark.
	 */
	logStartupPhase: (name: string, sinceStartMs: number | null) => __TAURI_INVOKE<void>("log_startup_phase", { name, sinceStartMs }),
	aiFetchStreamStart: (req: AiFetchRequest) => typedError<string, string>(__TAURI_INVOKE("ai_fetch_stream_start", { req })),
	aiFetchStreamCancel: (streamId: string) => typedError<null, string>(__TAURI_INVOKE("ai_fetch_stream_cancel", { streamId })),
	listAiSessions: (projectDir: string, kind: AiSessionKind) => typedError<AiSessionFile[], string>(__TAURI_INVOKE("list_ai_sessions", { projectDir, kind })),
	readAiSession: (projectDir: string, kind: AiSessionKind, id: string) => typedError<string | null, string>(__TAURI_INVOKE("read_ai_session", { projectDir, kind, id })),
	writeAiSession: (projectDir: string, kind: AiSessionKind, id: string, bodyJson: string) => typedError<null, string>(__TAURI_INVOKE("write_ai_session", { projectDir, kind, id, bodyJson })),
	deleteAiSession: (projectDir: string, kind: AiSessionKind, id: string) => typedError<null, string>(__TAURI_INVOKE("delete_ai_session", { projectDir, kind, id })),
	listAiPromptAssets: (projectDir: string) => typedError<AiPromptAssets, string>(__TAURI_INVOKE("list_ai_prompt_assets", { projectDir })),
	writeAiMemory: (projectDir: string, body: string) => typedError<null, string>(__TAURI_INVOKE("write_ai_memory", { projectDir, body })),
	saveAiChat: (projectDir: string, filename: string, body: string) => typedError<string, string>(__TAURI_INVOKE("save_ai_chat", { projectDir, filename, body })),
	claudeCliDetect: () => __TAURI_INVOKE<{
	path: string,
	version: string | null,
} | null>("claude_cli_detect"),
	claudeCliSpawn: (req: ClaudeSpawnRequest) => typedError<string, string>(__TAURI_INVOKE("claude_cli_spawn", { req })),
	claudeCliSend: (sessionId: string, line: string) => typedError<null, string>(__TAURI_INVOKE("claude_cli_send", { sessionId, line })),
	claudeCliKill: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("claude_cli_kill", { sessionId })),
	codexCliDetect: () => __TAURI_INVOKE<{
	path: string,
	version: string | null,
} | null>("codex_cli_detect"),
	codexCliTurn: (req: CodexTurnRequest) => typedError<string, string>(__TAURI_INVOKE("codex_cli_turn", { req })),
	codexCliKill: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("codex_cli_kill", { sessionId })),
	refreshMenu: (labels: MenuLabels, recent: RecentEntry[]) => typedError<null, string>(__TAURI_INVOKE("refresh_menu", { labels, recent })),
	/**
	 *  Match the NSWindow's appearance to the app theme so the system-drawn
	 *  title-bar chrome (top-edge highlight, traffic-light hover states) blends
	 *  in. Without this, a dark-themed app on a default-appearance NSWindow gets
	 *  a bright 1px highlight at the very top, because macOS draws the highlight
	 *  for *light* windows.
	 *
	 *  No-op on non-macOS and on macOS versions predating `NSAppearance` (which
	 *  effectively means no-op if the selector doesn't exist).
	 */
	setWindowAppearance: (dark: boolean) => __TAURI_INVOKE<void>("set_window_appearance", { dark }),
	/**
	 *  Open the native WebView developer tools for this window. Compiled in all
	 *  builds because the `devtools` Cargo feature is enabled by default (see
	 *  Cargo.toml). Gated in the UI behind Developer Mode (F12).
	 */
	openDevtools: () => __TAURI_INVOKE<void>("open_devtools"),
	getSyncConfig: (projectDir: string) => typedError<SyncConfigMasked, string>(__TAURI_INVOKE("get_sync_config", { projectDir })),
	saveSyncConfig: (projectDir: string, config: SyncConfig) => typedError<null, string>(__TAURI_INVOKE("save_sync_config", { projectDir, config })),
	syncNow: (projectDir: string) => typedError<SyncStatus, string>(__TAURI_INVOKE("sync_now", { projectDir })),
	testSyncConnection: (webdavUrl: string, username: string, password: string) => typedError<boolean, string>(__TAURI_INVOKE("test_sync_connection", { webdavUrl, username, password })),
};

/* Types */
export type AiFetchRequest = {
	/**
	 *  Full URL. Must be https:// (http:// allowed only for localhost for
	 *  self-hosted / ollama during development).
	 */
	url: string,
	headers: ([string, string])[],
	/**  Raw JSON body. The caller (plugin) owns the shape — we just POST it. */
	body: string,
	/**
	 *  When true, parse the response as SSE (split on `\n\n`, strip `data: `,
	 *  skip `[DONE]`). When false, buffer the full body and emit one chunk.
	 */
	sse: boolean,
};

export type AiPromptAsset = {
	id: string,
	kind: string,
	path: string,
	name: string,
	content: string,
};

export type AiPromptAssets = {
	commands: AiPromptAsset[],
	skills: AiPromptAsset[],
	memory: AiPromptAsset | null,
};

export type AiSessionFile = {
	id: string,
	kind: AiSessionKind,
	path: string,
	updatedAt: number | null,
};

export type AiSessionKind = "talk" | "agent";

/**
 *  Whether the caller can subsequently `update` a verified remote
 *  identity via the standard `PublishInput.update_target` flow, or the
 *  provider/API state requires a separate, explicit user action such as
 *  creating a new copy.
 */
export type BindingCapability =
/**
 *  Ghost, WordPress self-hosted, WordPress.com. Persist the returned
 *  typed revision as `RemoteIdentity.provider_revision` and the
 *  legacy flat value as `RemoteIdentity.revision`; the typed value is
 *  ready to feed `UpdateTarget.expected_revision` on the next publish.
 */
{ kind: "updatable" } |
/**
 *  Verified remote identity exists, but the provider/API cannot
 *  update it in place. This type remains useful for verified create
 *  results and a future explicit New Copy flow; Task 20 must not
 *  manufacture it for unverifiable Medium legacy-post binds.
 */
{ kind: "unsupported_update"; data: {
	reason: UnsupportedUpdateReason,
} };

/**
 *  Body format selector. Ghost / WordPress consume HTML; Medium
 *  consumes Markdown natively.
 */
export type BodyFormat = "html" | "markdown";

export type ChannelConfig = {
	/**  Stable UUID. Survives renaming the user-facing label. */
	id: string,
	/**  User-facing label, e.g. "Personal Ghost". */
	name: string,
} & PlatformConfig;

/**
 *  Per-channel state: the last saved form the user typed, the remote
 *  post identity if any, and the cover reference if any.
 */
export type ChannelState = ChannelState_Serialize | ChannelState_Deserialize;

/**
 *  Per-channel state: the last saved form the user typed, the remote
 *  post identity if any, and the cover reference if any.
 */
export type ChannelState_Deserialize = {
	form?: FormDraft_Deserialize,
	remote?: RemoteIdentity_Deserialize | null,
	cover?: CoverRef | null,
};

/**
 *  Per-channel state: the last saved form the user typed, the remote
 *  post identity if any, and the cover reference if any.
 */
export type ChannelState_Serialize = {
	form: FormDraft_Serialize,
	remote?: RemoteIdentity_Serialize | null,
	cover?: CoverRef | null,
};

export type ChapterStats = {
	file_name: string,
	file_path: string,
	word_count: number,
};

export type ClaudeSpawnRequest = {
	/**  Override the auto-detected CLI path. */
	cli_path: string | null,
	/**  Working directory for the spawned process. Default: inherit. */
	cwd: string | null,
	system_prompt: string | null,
	/**  Extra `--add-dir` values (plugin usually includes the project root). */
	add_dirs: string[],
	/**
	 *  One of: "acceptEdits", "auto", "bypassPermissions", "default",
	 *  "dontAsk", "plan". Passed through as-is.
	 */
	permission_mode: string | null,
	model: string | null,
	/**  Plugin-owned UUID; must be a valid UUID string on the CLI side. */
	session_uuid: string,
	/**
	 *  Resume an existing CLI conversation instead of creating a new one.
	 *  The CLI rejects `--session-id` values it has already seen (the
	 *  process exits immediately, which surfaced as "Unknown claude
	 *  session" on the next send), so re-spawns of a session that already
	 *  produced output MUST pass `--resume` instead.
	 */
	resume?: boolean,
	/**
	 *  Extra CLI args (escape hatch). Validated against a blocklist of
	 *  flags we manage ourselves.
	 */
	extra_args: string[],
};

/**
 *  Payload emitted as the `cli-open` event on hot path (existing instance
 *  receives a second invocation). The frontend routes folders to new windows
 *  and files to either the focused single-file window or a new window.
 */
export type CliOpenPayload = {
	files: PendingFile[],
	folders: string[],
	force_new_window: boolean,
	/**
	 *  Label of the single window meant to handle this event. On Windows,
	 *  `emit_to` broadcasts to every webview, so the frontend filters on this
	 *  to keep the "single coordinator" semantics (see app-events listeners).
	 */
	target_label: string,
};

export type CliShimStatus = {
	/**  Where the shim would (or does) live on this platform. */
	install_path: string,
	/**  True if the file at `install_path` exists. */
	installed: boolean,
	/**  True if `installed` AND it points at the bundled shim we ship now. */
	up_to_date: boolean,
	/**  Path to the bundled shim — what would be linked/copied. */
	source_path: string,
};

/**
 *  PNG-encoded image bytes pulled from the system clipboard via the
 *  Rust-side `arboard` API. Reading via Rust (instead of the browser's
 *  `navigator.clipboard.read()`) avoids the WebKit/macOS "Paste"
 *  permission prompt that otherwise pops up next to the cursor.
 */
export type ClipboardImage = {
	bytes: number[],
	mime: string,
	width: number,
	height: number,
};

export type CodexTurnRequest = {
	/**  Override the auto-detected CLI path. */
	cli_path: string | null,
	/**  Working directory / agent workspace root. */
	cwd: string | null,
	/**  Model id (passed as `-m`). Empty/None → Codex picks its default. */
	model: string | null,
	/**  Sandbox policy: "read-only", "workspace-write", or "danger-full-access". */
	sandbox: string | null,
	/**  Extra writable directories (`--add-dir`). */
	add_dirs: string[],
	/**  The user prompt for this turn (sent via stdin). */
	prompt: string,
	/**
	 *  When set, resume the existing Codex conversation
	 *  (`codex exec … resume <thread_id>`) instead of starting a new one.
	 */
	resume_thread_id: string | null,
	/**  Caller-owned id used to key the Tauri event channel + kill registry. */
	session_uuid: string,
};

/**
 *  Reference to a stored cover asset. Serialized inside the Publish
 *  sidecar's per-channel state.
 *
 *  * `content_hash` is the hex BLAKE3 digest of the raw bytes; it doubles
 *    as the on-disk filename stem so the reference is durable across
 *    application restarts and repository moves.
 *  * `extension` is the canonical lowercase file extension we assigned
 *    at write time (`"png"` / `"jpg"` / `"gif"` / `"webp"`).
 *  * `mime` is the content-derived MIME string (never the caller's
 *    claimed value).
 *  * `bytes` is the raw payload length; used at cleanup time to catch
 *    accidental truncation.
 */
export type CoverRef = {
	content_hash: string,
	extension: string,
	mime: string,
	bytes: number,
};

export type CreateLiteraryStudyProjectRequest = {
	projectName: string,
	parentDir: string,
	sourcePath: string,
	title: string,
	author: string | null,
	language: string | null,
	chapters: LiteraryChapterDraft[],
};

export type CreateLiteraryStudyProjectResult = {
	projectPath: string,
	firstChapterPath: string,
	chapterCount: number,
};

export type DailyStats = {
	date: string,
	words_written: number,
	time_minutes: number,
};

export type DetectedCli = {
	path: string,
	version: string | null,
};

export type EffectiveSettings = {
	view: ResolvedView,
	new_file: ResolvedNewFile,
	plugins: ResolvedPlugins,
	/**  True when a project is open — lets the UI show project-vs-global affordances. */
	is_project_scoped: boolean,
};

export type ExportProjectResult = ExportProjectResult_Serialize | ExportProjectResult_Deserialize;

export type ExportProjectResult_Deserialize = {
	message: string,
	warning?: PandocFailure_Deserialize | null,
};

export type ExportProjectResult_Serialize = {
	message: string,
	warning?: PandocFailure_Serialize | null,
};

export type ExternalFileChangePayload = {
	/**  Canonical path used as the stable identity for watcher and poll dedupe. */
	identity: string,
	/**  Every currently registered frontend path for this identity. */
	paths: string[],
};

export type FileEntry = {
	name: string,
	path: string,
	is_dir: boolean,
	size: number,
	/**  Unix epoch milliseconds; None when filesystem doesn't expose mtime. */
	mtime: number | null,
	/**
	 *  Unix epoch milliseconds for filesystem creation/birth time. None on
	 *  platforms or filesystems that don't expose it (e.g. older ext4).
	 */
	ctime: number | null,
};

/**
 *  The strictly-user-editable subset of the Publish dialog. Additions
 *  here MUST also appear in the "no credential / no transient state"
 *  tests below.
 */
export type FormDraft = FormDraft_Serialize | FormDraft_Deserialize;

/**
 *  The strictly-user-editable subset of the Publish dialog. Additions
 *  here MUST also appear in the "no credential / no transient state"
 *  tests below.
 */
export type FormDraft_Deserialize = {
	title?: string,
	tags?: string[],
	excerpt?: string | null,
	slug?: string | null,
	status?: string | null,
	destination?: string | null,
};

/**
 *  The strictly-user-editable subset of the Publish dialog. Additions
 *  here MUST also appear in the "no credential / no transient state"
 *  tests below.
 */
export type FormDraft_Serialize = {
	title: string,
	tags: string[],
	excerpt?: string | null,
	slug?: string | null,
	status?: string | null,
	destination?: string | null,
};

/**  Shape written to `~/.novelist/settings.json`. */
export type GlobalSettings = GlobalSettings_Serialize | GlobalSettings_Deserialize;

/**  Shape written to `~/.novelist/settings.json`. */
export type GlobalSettings_Deserialize = {
	view?: ViewConfig_Deserialize,
	new_file?: NewFileConfig_Deserialize,
	plugins?: PluginsConfig,
	/**
	 *  Image-host providers and active-host pointer. Credentials live
	 *  here only — never in per-project settings.
	 */
	image_hosts?: ImageHostSettings_Deserialize,
	/**
	 *  Publish channels (Ghost / WordPress / Medium). Credentials live
	 *  here only — same convention as image_hosts.
	 */
	publish?: PublishSettings,
	/**
	 *  Optional override path to the Pandoc binary. When unset (or
	 *  empty), Novelist auto-detects Pandoc from `$PATH` and common
	 *  install locations. Pandoc is NOT bundled with Novelist — users
	 *  without it installed are pointed at https://pandoc.org/installing.html.
	 */
	pandoc_path?: string | null,
};

/**  Shape written to `~/.novelist/settings.json`. */
export type GlobalSettings_Serialize = {
	view: ViewConfig_Serialize,
	new_file: NewFileConfig_Serialize,
	plugins: PluginsConfig,
	/**
	 *  Image-host providers and active-host pointer. Credentials live
	 *  here only — never in per-project settings.
	 */
	image_hosts: ImageHostSettings_Serialize,
	/**
	 *  Publish channels (Ghost / WordPress / Medium). Credentials live
	 *  here only — same convention as image_hosts.
	 */
	publish: PublishSettings,
	/**
	 *  Optional override path to the Pandoc binary. When unset (or
	 *  empty), Novelist auto-detects Pandoc from `$PATH` and common
	 *  install locations. Pandoc is NOT bundled with Novelist — users
	 *  without it installed are pointed at https://pandoc.org/installing.html.
	 */
	pandoc_path?: string | null,
};

export type HostConfig = HostConfig_Serialize | HostConfig_Deserialize;

export type HostConfig_Deserialize = {
	/**  Stable UUID. Survives renaming the user-facing label. */
	id: string,
	/**  User-facing label, e.g. "Personal R2". */
	name: string,
} & ProviderConfig_Deserialize;

export type HostConfig_Serialize = {
	/**  Stable UUID. Survives renaming the user-facing label. */
	id: string,
	/**  User-facing label, e.g. "Personal R2". */
	name: string,
} & ProviderConfig_Serialize;

export type ImageHostSettings = ImageHostSettings_Serialize | ImageHostSettings_Deserialize;

export type ImageHostSettings_Deserialize = {
	hosts?: HostConfig_Deserialize[],
	active_host_id?: string | null,
	auto_on_paste?: boolean,
};

export type ImageHostSettings_Serialize = {
	hosts: HostConfig_Serialize[],
	active_host_id?: string | null,
	auto_on_paste: boolean,
};

export type LiteraryChapterDraft = {
	id: string,
	volume: string | null,
	title: string,
	text: string,
};

export type LiterarySourceInspection = {
	title: string,
	author: string | null,
	language: string | null,
	sourcePath: string,
	chapters: LiteraryChapterDraft[],
};

export type ManagedNameStateV1 = {
	version: number,
	status: ManagedNameStatus,
	templateRaw: string,
	currentH1: string,
	documentKey: string,
};

export type ManagedNameStatus = "managed" | "detached";

/**
 *  All human-readable labels used in the menu. The frontend builds
 *  this from the i18n store for the current locale. Every field must
 *  be present — fall back to the English string on the frontend if a
 *  translation is missing.
 */
export type MenuLabels = {
	file_menu: string,
	edit_menu: string,
	view_menu: string,
	window_menu: string,
	help_menu: string,
	about_novelist: string,
	settings: string,
	new_file: string,
	new_window: string,
	new_project: string,
	open_file: string,
	open_directory: string,
	open_recent: string,
	no_recent: string,
	open_containing_folder: string,
	switch_project: string,
	rename_file: string,
	move_file: string,
	save_as_template: string,
	export_project: string,
	close_tab: string,
	find_in_project: string,
	go_to_line: string,
	bold: string,
	italic: string,
	strikethrough: string,
	insert_link: string,
	inline_code: string,
	toggle_heading: string,
	copy_rich_text: string,
	copy_plain_text: string,
	simplified_to_traditional: string,
	traditional_to_simplified: string,
	generate_pinyin: string,
	command_palette: string,
	toggle_sidebar: string,
	toggle_outline: string,
	toggle_zen: string,
	toggle_draft: string,
	toggle_snapshot: string,
	toggle_stats: string,
	toggle_template: string,
	toggle_mindmap: string,
	toggle_split: string,
	check_for_updates: string,
};

/**  New-file template preferences. */
export type NewFileConfig = NewFileConfig_Serialize | NewFileConfig_Deserialize;

/**  New-file template preferences. */
export type NewFileConfig_Deserialize = {
	template?: string | null,
	detect_from_folder?: boolean | null,
	auto_rename_from_h1?: boolean | null,
	/**
	 *  User-pinned default location for new files. Absolute path. When set,
	 *  Cmd+N always creates here regardless of the recent activity pointer.
	 *  `None` means "follow the last-used tracker."
	 */
	default_dir?: string | null,
	/**
	 *  Live pointer: directory of the most recently created file. Updated
	 *  after every successful create (header button, Cmd+N, per-folder
	 *  context menu). Seeded to the project root on first open.
	 */
	last_used_dir?: string | null,
};

/**  New-file template preferences. */
export type NewFileConfig_Serialize = {
	template?: string | null,
	detect_from_folder?: boolean | null,
	auto_rename_from_h1?: boolean | null,
	/**
	 *  User-pinned default location for new files. Absolute path. When set,
	 *  Cmd+N always creates here regardless of the recent activity pointer.
	 *  `None` means "follow the last-used tracker."
	 */
	default_dir?: string | null,
	/**
	 *  Live pointer: directory of the most recently created file. Updated
	 *  after every successful create (header button, Cmd+N, per-folder
	 *  context menu). Seeded to the project root on first open.
	 */
	last_used_dir?: string | null,
};

export type OutlineConfig = {
	order?: string[],
};

/**
 *  A structured diagnostic emitted by every failure path in this
 *  module. Serializable to JSON for logs and IPC — safe by construction.
 */
export type PandocFailure = PandocFailure_Serialize | PandocFailure_Deserialize;

/**
 *  A structured diagnostic emitted by every failure path in this
 *  module. Serializable to JSON for logs and IPC — safe by construction.
 */
export type PandocFailure_Deserialize = {
	/**  Which point in the pipeline failed. Always populated. */
	stage: PandocStage,
	/**
	 *  User-facing English message. Never contains secrets or document
	 *  contents — safe to render verbatim.
	 */
	message: string,
	/**
	 *  Absolute path of the resolved Pandoc binary when known.
	 *  `None` on `Discovery` failures.
	 */
	resolved_binary?: string | null,
	/**  Target output format ("html" / "pdf" / "docx" / "epub" / …). */
	format?: string | null,
	/**
	 *  Sanitized argv summary — each user-supplied `--flag=value` has
	 *  its value redacted if the flag name suggests a secret. Positional
	 *  paths remain visible; environment is NEVER included.
	 */
	argv_summary?: string[],
	/**
	 *  Exit code, when applicable (`ExitNonZero` and sometimes
	 *  `TimeoutOrCancel`). Killed-by-signal → `None`.
	 */
	exit_code?: number | null,
	/**
	 *  Truncated stderr, always <= [`STDERR_BUDGET`] bytes, cut at a
	 *  UTF-8 code-point boundary. Empty when no stderr was emitted.
	 */
	stderr_excerpt?: string,
	/**
	 *  Whether `stderr_excerpt` was truncated below the original
	 *  length. Lets callers show a "(truncated)" hint.
	 */
	stderr_truncated?: boolean,
	/**
	 *  Optional source-file context (path only — never contents).
	 *  Populated on `InputRead` and on export runs where the caller
	 *  wants the diagnostic to name the offending file.
	 */
	source_path?: string | null,
	/**
	 *  Optional list of paths probed during `Discovery`, so the UI
	 *  can show "we looked here, here, and here" without a full
	 *  environment dump.
	 */
	probed_paths?: string[],
};

/**
 *  A structured diagnostic emitted by every failure path in this
 *  module. Serializable to JSON for logs and IPC — safe by construction.
 */
export type PandocFailure_Serialize = {
	/**  Which point in the pipeline failed. Always populated. */
	stage: PandocStage,
	/**
	 *  User-facing English message. Never contains secrets or document
	 *  contents — safe to render verbatim.
	 */
	message: string,
	/**
	 *  Absolute path of the resolved Pandoc binary when known.
	 *  `None` on `Discovery` failures.
	 */
	resolved_binary?: string | null,
	/**  Target output format ("html" / "pdf" / "docx" / "epub" / …). */
	format?: string | null,
	/**
	 *  Sanitized argv summary — each user-supplied `--flag=value` has
	 *  its value redacted if the flag name suggests a secret. Positional
	 *  paths remain visible; environment is NEVER included.
	 */
	argv_summary?: string[],
	/**
	 *  Exit code, when applicable (`ExitNonZero` and sometimes
	 *  `TimeoutOrCancel`). Killed-by-signal → `None`.
	 */
	exit_code?: number | null,
	/**
	 *  Truncated stderr, always <= [`STDERR_BUDGET`] bytes, cut at a
	 *  UTF-8 code-point boundary. Empty when no stderr was emitted.
	 */
	stderr_excerpt?: string,
	/**
	 *  Whether `stderr_excerpt` was truncated below the original
	 *  length. Lets callers show a "(truncated)" hint.
	 */
	stderr_truncated?: boolean,
	/**
	 *  Optional source-file context (path only — never contents).
	 *  Populated on `InputRead` and on export runs where the caller
	 *  wants the diagnostic to name the offending file.
	 */
	source_path?: string | null,
	/**
	 *  Optional list of paths probed during `Discovery`, so the UI
	 *  can show "we looked here, here, and here" without a full
	 *  environment dump.
	 */
	probed_paths?: string[],
};

/**
 *  One of the well-defined stages at which a Pandoc export can fail.
 *
 *  Serialization is `snake_case` so a frontend can pattern-match on
 *  the string without a codegen dependency.
 */
export type PandocStage =
/**
 *  The binary could not be located via override, PATH, or the
 *  deterministic probe list.
 */
"discovery" |
/**
 *  Reading the input file or decoding its legacy-encoded bytes as
 *  text failed before Pandoc was spawned.
 */
"input_read" |
/**
 *  The child process could not be spawned (e.g. permission denied
 *  after resolution, missing dylib, or fork failure).
 */
"spawn" |
/**
 *  The wait on the child was aborted because it exceeded the
 *  caller-supplied timeout, or the caller cancelled the export.
 *  File export uses the 120-second default.
 */
"timeout_or_cancel" |
/**
 *  Pandoc returned a non-zero exit code. `exit_code` is populated
 *  with the OS-reported value (or `None` if killed by a signal).
 */
"exit_non_zero" |
/**
 *  Pandoc succeeded but its stdout could not be decoded (only
 *  applicable to the stdin/stdout HTML variant). The file-output
 *  path never triggers this because Pandoc writes bytes directly.
 */
"output_decode" |
/**
 *  Pandoc completed, but its sibling temporary output could not be
 *  durably committed to the user-selected destination.
 */
"output_commit" |
/**
 *  Post-run cleanup (temp-file removal, kill/reap on cancel, etc.)
 *  failed. This is informational — the export itself may still
 *  have succeeded — but we surface it so the UI can hint at disk
 *  full / permission issues.
 */
"cleanup";

export type PandocStatus = PandocStatus_Serialize | PandocStatus_Deserialize;

export type PandocStatus_Deserialize = {
	available: boolean,
	version: string | null,
	/**
	 *  Absolute path of the resolved binary, when found. Useful for
	 *  the Settings UI to confirm what we're actually invoking.
	 */
	resolved_path?: string | null,
	/**
	 *  The user's saved override (mirrors `GlobalSettings.pandoc_path`)
	 *  — surfaced so the Settings form can pre-fill the input.
	 */
	override_path?: string | null,
};

export type PandocStatus_Serialize = {
	available: boolean,
	version: string | null,
	/**
	 *  Absolute path of the resolved binary, when found. Useful for
	 *  the Settings UI to confirm what we're actually invoking.
	 */
	resolved_path?: string | null,
	/**
	 *  The user's saved override (mirrors `GlobalSettings.pandoc_path`)
	 *  — surfaced so the Settings form can pre-fill the input.
	 */
	override_path?: string | null,
};

export type PendingFile = {
	path: string,
	line: number | null,
	col: number | null,
};

export type PlatformConfig = { platform: "ghost";
/**  Admin URL ending without a slash, e.g. "https://blog.example.com". */
admin_url: string;
/**  Admin API key in the canonical "<id>:<secret_hex>" form. */
api_key: string } | { platform: "wordpress_self_hosted";
/**  Site URL ending without a slash, e.g. "https://blog.example.com". */
site_url: string; username: string;
/**
 *  Application Password, the 24-char string from WP Admin →
 *  Users → Application Passwords. Spaces optional.
 */
app_password: string } | { platform: "wordpress_com";
/**  Site id (numeric) or domain ("myblog.wordpress.com"). */
site_id_or_domain: string;
/**  OAuth2 access token from developer.wordpress.com. */
access_token: string } | { platform: "medium";
/**
 *  Integration token from Settings → Security → Integration
 *  Tokens. The Medium UI for generating new tokens was removed
 *  in late 2024; legacy users only.
 */
token: string };

export type PluginInfo = {
	id: string,
	name: string,
	version: string,
	permissions: string[],
	active: boolean,
	ui: PluginUiConfig | null,
	description: string | null,
	author: string | null,
	icon: string | null,
	builtin: boolean,
	enabled: boolean,
};

export type PluginReplacementResult = {
	from: number,
	to: number,
	text: string,
};

export type PluginUiConfig = {
	type: string,
	entry: string,
	width?: number | null,
	label?: string | null,
	file_extensions?: string[] | null,
	/**
	 *  Whether the file handler should appear in generic "new file" menus.
	 *  Import-driven formats such as `.litstudy` set this to false.
	 */
	creatable?: boolean | null,
	/**
	 *  UI plugins loaded in isolated webviews need an app relaunch after
	 *  enable/disable so every window rebuilds the extension registry.
	 */
	requires_app_reload?: boolean,
};

/**
 *  Per-plugin enable flags. Project-level map stores only entries that
 *  differ from the global default.
 */
export type PluginsConfig = {
	enabled?: { [key in string]: boolean },
};

export type PortableModeInfo = {
	enabled: boolean,
	data_root: string,
};

/**
 *  Returns `(hosted_url, attachment_id_or_zero)`. Only WordPress
 *  returns a non-zero attachment id (used for `featured_media`).
 */
export type PostImageUploadResult = {
	url: string,
	attachment_id: number,
};

export type ProjectConfig = ProjectConfig_Serialize | ProjectConfig_Deserialize;

export type ProjectConfig_Deserialize = {
	project: ProjectMeta,
	outline?: OutlineConfig,
	writing?: WritingConfig,
	/**  Sidebar/file-tree view preferences. Overrides global `~/.novelist/settings.json`. */
	view?: ViewConfig_Deserialize,
	/**  New-file template preferences. Overrides global. */
	new_file?: NewFileConfig_Deserialize,
	/**  Per-plugin enable flags (deltas from the global default map). */
	plugins?: PluginsConfig,
	/**
	 *  Per-project override for which image host is active. Credentials
	 *  stay in global settings — only the pointer to a configured host
	 *  can be overridden here.
	 */
	active_image_host_id?: string | null,
};

export type ProjectConfig_Serialize = {
	project: ProjectMeta,
	outline: OutlineConfig,
	writing: WritingConfig,
	/**  Sidebar/file-tree view preferences. Overrides global `~/.novelist/settings.json`. */
	view?: ViewConfig_Serialize,
	/**  New-file template preferences. Overrides global. */
	new_file?: NewFileConfig_Serialize,
	/**  Per-plugin enable flags (deltas from the global default map). */
	plugins?: PluginsConfig,
	/**
	 *  Per-project override for which image host is active. Credentials
	 *  stay in global settings — only the pointer to a configured host
	 *  can be overridden here.
	 */
	active_image_host_id?: string | null,
};

export type ProjectMeta = {
	name: string,
	type?: string,
	version?: string,
};

export type ProviderConfig = ProviderConfig_Serialize | ProviderConfig_Deserialize;

export type ProviderConfig_Deserialize = ({ provider: "qiniu"; access_key: string; secret_key: string; bucket: string;
/**  CDN domain that fronts the bucket, e.g. "https://cdn.example.com". */
domain: string }) & { access_key_id?: never; access_key_secret?: never; api_token?: never; bearer?: never; client_id?: never; custom_domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never } | ({ provider: "aliyun_oss"; access_key_id: string; access_key_secret: string; bucket: string;
/**  Region endpoint, e.g. "oss-cn-hangzhou.aliyuncs.com". */
endpoint: string; custom_domain?: string | null }) & { access_key?: never; api_token?: never; bearer?: never; client_id?: never; domain?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "s3"; access_key_id: string; secret_access_key: string; bucket: string; region: string;
/**  Set for non-AWS S3-compatible endpoints (R2, MinIO). */
endpoint?: string | null;
/**  Optional key prefix prepended before the generated object key. */
path_prefix?: string | null;
/**  Custom CDN domain. Final URL = `<custom_domain>/<key>` when set. */
custom_domain?: string | null }) & { access_key?: never; access_key_secret?: never; api_token?: never; bearer?: never; client_id?: never; domain?: never; post_url?: never; secret_key?: never } | ({ provider: "imgur"; client_id: string }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; api_token?: never; bearer?: never; bucket?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "smms"; api_token?: string | null }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; bearer?: never; bucket?: never; client_id?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "custom"; post_url: string; bearer?: string | null }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; api_token?: never; bucket?: never; client_id?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; region?: never; secret_access_key?: never; secret_key?: never };

export type ProviderConfig_Serialize = ({ provider: "qiniu"; access_key: string; secret_key: string; bucket: string;
/**  CDN domain that fronts the bucket, e.g. "https://cdn.example.com". */
domain: string }) & { access_key_id?: never; access_key_secret?: never; api_token?: never; bearer?: never; client_id?: never; custom_domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never } | ({ provider: "aliyun_oss"; access_key_id: string; access_key_secret: string; bucket: string;
/**  Region endpoint, e.g. "oss-cn-hangzhou.aliyuncs.com". */
endpoint: string; custom_domain?: string | null }) & { access_key?: never; api_token?: never; bearer?: never; client_id?: never; domain?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "s3"; access_key_id: string; secret_access_key: string; bucket: string; region: string;
/**  Set for non-AWS S3-compatible endpoints (R2, MinIO). */
endpoint?: string | null;
/**  Optional key prefix prepended before the generated object key. */
path_prefix?: string | null;
/**  Custom CDN domain. Final URL = `<custom_domain>/<key>` when set. */
custom_domain?: string | null }) & { access_key?: never; access_key_secret?: never; api_token?: never; bearer?: never; client_id?: never; domain?: never; post_url?: never; secret_key?: never } | ({ provider: "imgur"; client_id: string }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; api_token?: never; bearer?: never; bucket?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "smms"; api_token?: string | null }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; bearer?: never; bucket?: never; client_id?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "custom"; post_url: string; bearer?: string | null }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; api_token?: never; bucket?: never; client_id?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; region?: never; secret_access_key?: never; secret_key?: never };

/**
 *  Provider-specific "modified" stamp echoed back on updates for
 *  optimistic concurrency. Internally-tagged `provider` discriminant
 *  mirrors [`crate::models::publish::PlatformConfig`] on the wire.
 *  Medium is intentionally absent (see
 *  [`PublishError::UnsupportedUpdate`]).
 */
export type ProviderRevision = ProviderRevision_Serialize | ProviderRevision_Deserialize;

/**
 *  Provider-specific "modified" stamp echoed back on updates for
 *  optimistic concurrency. Internally-tagged `provider` discriminant
 *  mirrors [`crate::models::publish::PlatformConfig`] on the wire.
 *  Medium is intentionally absent (see
 *  [`PublishError::UnsupportedUpdate`]).
 */
export type ProviderRevision_Deserialize =
/**
 *  Ghost's `updated_at`, ISO-8601 UTC. Ghost's Admin API
 *  requires the caller to echo this exact string back in a
 *  `PUT /posts/:id` body or the update is rejected 409.
 */
({ provider: "ghost"; updated_at: string }) & { modified?: never; modified_gmt?: never } |
/**
 *  WordPress's `modified` / `modified_gmt`. Both optional
 *  because the WP REST API does not enforce echoing them; they
 *  are informational for drift detection.
 */
({ provider: "wordpress"; modified?: string | null; modified_gmt?: string | null }) & { updated_at?: never };

/**
 *  Provider-specific "modified" stamp echoed back on updates for
 *  optimistic concurrency. Internally-tagged `provider` discriminant
 *  mirrors [`crate::models::publish::PlatformConfig`] on the wire.
 *  Medium is intentionally absent (see
 *  [`PublishError::UnsupportedUpdate`]).
 */
export type ProviderRevision_Serialize =
/**
 *  Ghost's `updated_at`, ISO-8601 UTC. Ghost's Admin API
 *  requires the caller to echo this exact string back in a
 *  `PUT /posts/:id` body or the update is rejected 409.
 */
({ provider: "ghost"; updated_at: string }) & { modified?: never; modified_gmt?: never } |
/**
 *  WordPress's `modified` / `modified_gmt`. Both optional
 *  because the WP REST API does not enforce echoing them; they
 *  are informational for drift detection.
 */
({ provider: "wordpress"; modified?: string | null; modified_gmt?: string | null }) & { updated_at?: never };

/**
 *  Durable cover payload returned to the Publish UI after store/load.
 *  `filename` and `mime` are canonical, content-derived metadata; `bytes`
 *  are runtime IPC data and are never serialized into the sidecar.
 */
export type PublishCoverAsset = {
	cover: CoverRef,
	bytes: number[],
	filename: string,
	mime: string,
};

/**
 *  All errors a publish adapter can return. Mapped to
 *  `AppError::Custom(...)` at the Tauri command boundary.
 *
 *  The new typed variants — [`Self::RemoteNotFound`],
 *  [`Self::UpdateConflict`], [`Self::UnsupportedUpdate`] — carry
 *  only structured provider/post context. No raw response bodies,
 *  no headers, no request bodies. If diagnostic detail from a
 *  provider response is ever added, it MUST be routed through
 *  [`redact_secrets`] first.
 *
 *  Wire representation is internally-tagged (`kind` + `data`) so a
 *  future command that wants to expose structured errors to the
 *  frontend has a stable JSON shape to depend on without changing
 *  the crate-wide `AppError` string contract. Existing publish
 *  commands still funnel through `From<PublishError> for AppError`
 *  as a Display string — see `core/src/commands/publish.rs`.
 *
 *  Display is implemented manually rather than via `#[error("...")]`
 *  so the serde `content = "data"` tuple-variant representation and
 *  the `Box<UpdateConflictContext>` payload access play together
 *  without thiserror's positional-arg parser choking on `.0.field`.
 */
export type PublishError = PublishError_Serialize | PublishError_Deserialize;

/**
 *  All errors a publish adapter can return. Mapped to
 *  `AppError::Custom(...)` at the Tauri command boundary.
 *
 *  The new typed variants — [`Self::RemoteNotFound`],
 *  [`Self::UpdateConflict`], [`Self::UnsupportedUpdate`] — carry
 *  only structured provider/post context. No raw response bodies,
 *  no headers, no request bodies. If diagnostic detail from a
 *  provider response is ever added, it MUST be routed through
 *  [`redact_secrets`] first.
 *
 *  Wire representation is internally-tagged (`kind` + `data`) so a
 *  future command that wants to expose structured errors to the
 *  frontend has a stable JSON shape to depend on without changing
 *  the crate-wide `AppError` string contract. Existing publish
 *  commands still funnel through `From<PublishError> for AppError`
 *  as a Display string — see `core/src/commands/publish.rs`.
 *
 *  Display is implemented manually rather than via `#[error("...")]`
 *  so the serde `content = "data"` tuple-variant representation and
 *  the `Box<UpdateConflictContext>` payload access play together
 *  without thiserror's positional-arg parser choking on `.0.field`.
 */
export type PublishError_Deserialize = { kind: "network"; data: string } | { kind: "auth"; data: string } | { kind: "quota_exceeded"; data: string } | { kind: "bad_config"; data: string } | { kind: "server"; data: {
	status: number,
	message: string,
} } | { kind: "unexpected_response"; data: string } | { kind: "pandoc_failed"; data: string } | { kind: "image_upload_failed"; data: {
	ref_path: string,
	cause: string,
} } |
/**
 *  Update targeted a post that no longer exists on the provider
 *  (or was never created there). Adapters map platform 404s on
 *  update endpoints to this. Safe by construction: only carries
 *  provider name and remote id.
 */
{ kind: "remote_not_found"; data: {
	provider: string,
	remote_id: string,
} } |
/**
 *  Optimistic-concurrency check failed: the caller's
 *  [`UpdateTarget::expected_revision`] does not match the
 *  provider's current revision. Adapters map platform 409s to
 *  this. Safe by construction: only structured revisions, not
 *  raw response bodies. Payload boxed so
 *  `Result<_, PublishError>` stays under Clippy's
 *  `result_large_err` size threshold.
 */
{ kind: "update_conflict"; data: UpdateConflictContext_Deserialize } |
/**
 *  Provider does not support updates. `reason` is a typed enum
 *  (see [`UnsupportedUpdateReason`]) — never a free-form string —
 *  so provider response text cannot leak here.
 */
{ kind: "unsupported_update"; data: {
	provider: string,
	reason: UnsupportedUpdateReason,
} };

/**
 *  All errors a publish adapter can return. Mapped to
 *  `AppError::Custom(...)` at the Tauri command boundary.
 *
 *  The new typed variants — [`Self::RemoteNotFound`],
 *  [`Self::UpdateConflict`], [`Self::UnsupportedUpdate`] — carry
 *  only structured provider/post context. No raw response bodies,
 *  no headers, no request bodies. If diagnostic detail from a
 *  provider response is ever added, it MUST be routed through
 *  [`redact_secrets`] first.
 *
 *  Wire representation is internally-tagged (`kind` + `data`) so a
 *  future command that wants to expose structured errors to the
 *  frontend has a stable JSON shape to depend on without changing
 *  the crate-wide `AppError` string contract. Existing publish
 *  commands still funnel through `From<PublishError> for AppError`
 *  as a Display string — see `core/src/commands/publish.rs`.
 *
 *  Display is implemented manually rather than via `#[error("...")]`
 *  so the serde `content = "data"` tuple-variant representation and
 *  the `Box<UpdateConflictContext>` payload access play together
 *  without thiserror's positional-arg parser choking on `.0.field`.
 */
export type PublishError_Serialize = { kind: "network"; data: string } | { kind: "auth"; data: string } | { kind: "quota_exceeded"; data: string } | { kind: "bad_config"; data: string } | { kind: "server"; data: {
	status: number,
	message: string,
} } | { kind: "unexpected_response"; data: string } | { kind: "pandoc_failed"; data: string } | { kind: "image_upload_failed"; data: {
	ref_path: string,
	cause: string,
} } |
/**
 *  Update targeted a post that no longer exists on the provider
 *  (or was never created there). Adapters map platform 404s on
 *  update endpoints to this. Safe by construction: only carries
 *  provider name and remote id.
 */
{ kind: "remote_not_found"; data: {
	provider: string,
	remote_id: string,
} } |
/**
 *  Optimistic-concurrency check failed: the caller's
 *  [`UpdateTarget::expected_revision`] does not match the
 *  provider's current revision. Adapters map platform 409s to
 *  this. Safe by construction: only structured revisions, not
 *  raw response bodies. Payload boxed so
 *  `Result<_, PublishError>` stays under Clippy's
 *  `result_large_err` size threshold.
 */
{ kind: "update_conflict"; data: UpdateConflictContext_Serialize } |
/**
 *  Provider does not support updates. `reason` is a typed enum
 *  (see [`UnsupportedUpdateReason`]) — never a free-form string —
 *  so provider response text cannot leak here.
 */
{ kind: "unsupported_update"; data: {
	provider: string,
	reason: UnsupportedUpdateReason,
} };

/**
 *  A per-channel snapshot of the persisted `FormDraft`s, plus the ids
 *  of any channel entries whose data could not be parsed cleanly.
 *
 *  This is the read shape for Task 14 (Publish form persistence): the
 *  dialog restores by document + stable channel id, and a corrupt
 *  entry for one channel MUST NOT hide sibling channels that are still
 *  valid on disk. The corrupt ids are surfaced so the UI can render a
 *  recoverable status without silently deleting or repairing the
 *  source of truth.
 */
export type PublishFormDraftsSnapshot = PublishFormDraftsSnapshot_Serialize | PublishFormDraftsSnapshot_Deserialize;

/**
 *  A per-channel snapshot of the persisted `FormDraft`s, plus the ids
 *  of any channel entries whose data could not be parsed cleanly.
 *
 *  This is the read shape for Task 14 (Publish form persistence): the
 *  dialog restores by document + stable channel id, and a corrupt
 *  entry for one channel MUST NOT hide sibling channels that are still
 *  valid on disk. The corrupt ids are surfaced so the UI can render a
 *  recoverable status without silently deleting or repairing the
 *  source of truth.
 */
export type PublishFormDraftsSnapshot_Deserialize = {
	/**
	 *  Channel id -> the last saved form for that channel. Only
	 *  entries whose per-channel `form` object round-tripped through
	 *  serde cleanly appear here.
	 */
	forms?: { [key in string]: FormDraft_Deserialize },
	/**
	 *  Channel ids whose disk data was skipped because the id itself
	 *  was invalid or its `form` object failed to parse. Sorted so the
	 *  wire order is stable for tests / UX comparisons.
	 */
	invalid_channel_ids?: string[],
};

/**
 *  A per-channel snapshot of the persisted `FormDraft`s, plus the ids
 *  of any channel entries whose data could not be parsed cleanly.
 *
 *  This is the read shape for Task 14 (Publish form persistence): the
 *  dialog restores by document + stable channel id, and a corrupt
 *  entry for one channel MUST NOT hide sibling channels that are still
 *  valid on disk. The corrupt ids are surfaced so the UI can render a
 *  recoverable status without silently deleting or repairing the
 *  source of truth.
 */
export type PublishFormDraftsSnapshot_Serialize = {
	/**
	 *  Channel id -> the last saved form for that channel. Only
	 *  entries whose per-channel `form` object round-tripped through
	 *  serde cleanly appear here.
	 */
	forms: { [key in string]: FormDraft_Serialize },
	/**
	 *  Channel ids whose disk data was skipped because the id itself
	 *  was invalid or its `form` object failed to parse. Sorted so the
	 *  wire order is stable for tests / UX comparisons.
	 */
	invalid_channel_ids: string[],
};

/**
 *  Inputs handed to a platform adapter's `publish()` function. The
 *  frontend builds this from the publish dialog plus pre-publish
 *  image rewrite. The optional [`Self::update_target`] field turns
 *  a call into an update instead of a create.
 */
export type PublishInput = PublishInput_Serialize | PublishInput_Deserialize;

/**
 *  Inputs handed to a platform adapter's `publish()` function. The
 *  frontend builds this from the publish dialog plus pre-publish
 *  image rewrite. The optional [`Self::update_target`] field turns
 *  a call into an update instead of a create.
 */
export type PublishInput_Deserialize = {
	title: string,
	/**
	 *  Already-rewritten body. For Ghost / WordPress this is HTML
	 *  (from Pandoc); for Medium this is Markdown.
	 */
	body: string,
	body_format: BodyFormat,
	tags?: string[],
	slug?: string | null,
	excerpt?: string | null,
	/**  Platform-specific status string. See per-platform spec. */
	status: string,
	/**  Already-uploaded feature image URL on the platform. */
	feature_image_url?: string | null,
	/**  WordPress-specific: pre-uploaded media attachment id. */
	featured_media_id?: number | null,
	/**
	 *  Medium-only: when set, post to a publication instead of the
	 *  authenticated user.
	 */
	publication_id?: string | null,
	/**
	 *  When set, updates the referenced remote post instead of
	 *  creating a new one. Absent (`None`) preserves legacy
	 *  create-only behavior for every existing caller.
	 */
	update_target?: UpdateTarget_Deserialize | null,
};

/**
 *  Inputs handed to a platform adapter's `publish()` function. The
 *  frontend builds this from the publish dialog plus pre-publish
 *  image rewrite. The optional [`Self::update_target`] field turns
 *  a call into an update instead of a create.
 */
export type PublishInput_Serialize = {
	title: string,
	/**
	 *  Already-rewritten body. For Ghost / WordPress this is HTML
	 *  (from Pandoc); for Medium this is Markdown.
	 */
	body: string,
	body_format: BodyFormat,
	tags: string[],
	slug?: string | null,
	excerpt?: string | null,
	/**  Platform-specific status string. See per-platform spec. */
	status: string,
	/**  Already-uploaded feature image URL on the platform. */
	feature_image_url?: string | null,
	/**  WordPress-specific: pre-uploaded media attachment id. */
	featured_media_id?: number | null,
	/**
	 *  Medium-only: when set, post to a publication instead of the
	 *  authenticated user.
	 */
	publication_id?: string | null,
	/**
	 *  When set, updates the referenced remote post instead of
	 *  creating a new one. Absent (`None`) preserves legacy
	 *  create-only behavior for every existing caller.
	 */
	update_target?: UpdateTarget_Serialize | null,
};

/**
 *  Whether an adapter created a new post or updated an existing one.
 *  Defaults to [`PublishOperation::Created`] so legacy on-disk
 *  sidecars and older frontends that omit the field parse cleanly.
 */
export type PublishOperation = "created" | "updated";

/**
 *  Result returned to the frontend on success. New fields
 *  [`Self::operation`] and [`Self::provider_revision`] are additive
 *  with `#[serde(default)]` so:
 *  1. Existing adapters using the [`Self::created`] builder stay
 *     forward-compatible.
 *  2. Legacy on-disk sidecars/frontends without these fields still
 *     deserialize (operation defaults to `Created`, revision to
 *     `None`).
 */
export type PublishResult = PublishResult_Serialize | PublishResult_Deserialize;

/**
 *  Result returned to the frontend on success. New fields
 *  [`Self::operation`] and [`Self::provider_revision`] are additive
 *  with `#[serde(default)]` so:
 *  1. Existing adapters using the [`Self::created`] builder stay
 *     forward-compatible.
 *  2. Legacy on-disk sidecars/frontends without these fields still
 *     deserialize (operation defaults to `Created`, revision to
 *     `None`).
 */
export type PublishResult_Deserialize = {
	/**  Canonical URL of the post on the platform. */
	url: string,
	/**  Platform post id (string for portability across platforms). */
	remote_id: string,
	/**
	 *  Whether this call created a new post or updated an existing
	 *  one. Defaults to `Created` for backward compatibility.
	 */
	operation?: PublishOperation,
	/**
	 *  Provider-typed revision stamp — Ghost's `updated_at`,
	 *  WordPress's `modified` fields. `None` for providers that
	 *  don't expose one (Medium) or callers that don't need it.
	 */
	provider_revision?: ProviderRevision_Deserialize | null,
};

/**
 *  Result returned to the frontend on success. New fields
 *  [`Self::operation`] and [`Self::provider_revision`] are additive
 *  with `#[serde(default)]` so:
 *  1. Existing adapters using the [`Self::created`] builder stay
 *     forward-compatible.
 *  2. Legacy on-disk sidecars/frontends without these fields still
 *     deserialize (operation defaults to `Created`, revision to
 *     `None`).
 */
export type PublishResult_Serialize = {
	/**  Canonical URL of the post on the platform. */
	url: string,
	/**  Platform post id (string for portability across platforms). */
	remote_id: string,
	/**
	 *  Whether this call created a new post or updated an existing
	 *  one. Defaults to `Created` for backward compatibility.
	 */
	operation: PublishOperation,
	/**
	 *  Provider-typed revision stamp — Ghost's `updated_at`,
	 *  WordPress's `modified` fields. `None` for providers that
	 *  don't expose one (Medium) or callers that don't need it.
	 */
	provider_revision?: ProviderRevision_Serialize | null,
};

export type PublishSettings = {
	channels?: ChannelConfig[],
};

/**
 *  Per-document Publish metadata. One file per document; one entry per
 *  stable channel id inside.
 *
 *  Serialization is via `serde_json::to_vec_pretty` (through Task 1's
 *  `atomic_write_json`) so sidecars are diff-friendly for the
 *  rename-migration and QA test harnesses.
 */
export type PublishSidecar = PublishSidecar_Serialize | PublishSidecar_Deserialize;

/**
 *  Per-document Publish metadata. One file per document; one entry per
 *  stable channel id inside.
 *
 *  Serialization is via `serde_json::to_vec_pretty` (through Task 1's
 *  `atomic_write_json`) so sidecars are diff-friendly for the
 *  rename-migration and QA test harnesses.
 */
export type PublishSidecar_Deserialize = {
	schema_version?: number,
	channels?: { [key in string]: ChannelState_Deserialize },
};

/**
 *  Per-document Publish metadata. One file per document; one entry per
 *  stable channel id inside.
 *
 *  Serialization is via `serde_json::to_vec_pretty` (through Task 1's
 *  `atomic_write_json`) so sidecars are diff-friendly for the
 *  rename-migration and QA test harnesses.
 */
export type PublishSidecar_Serialize = {
	schema_version: number,
	channels: { [key in string]: ChannelState_Serialize },
};

/**
 *  An entry shown under the Open Recent submenu. Name is the display
 *  label; path is the absolute directory path used as the menu item ID
 *  suffix.
 */
export type RecentEntry = {
	name: string,
	path: string,
};

export type RecentProject = {
	path: string,
	name: string,
	last_opened: string,
	/**
	 *  `true` keeps the project above all unpinned ones. Optional in the
	 *  persisted JSON so pre-existing files deserialize cleanly.
	 */
	pinned?: boolean,
	/**
	 *  Manual rank within the pinned / unpinned group. Smaller = earlier.
	 *  `None` falls back to `last_opened` order. Optional for back-compat.
	 */
	sort_order?: number | null,
};

export type RegisteredCommandInfo = {
	plugin_id: string,
	command_id: string,
	label: string,
};

/**
 *  The identity of a post on the remote platform, once we've created or
 *  bound one. `revision` is the legacy flat string retained for old
 *  sidecars; `provider_revision` is the durable typed revision used by
 *  current publish/update flows.
 */
export type RemoteIdentity = RemoteIdentity_Serialize | RemoteIdentity_Deserialize;

/**
 *  The identity of a post on the remote platform, once we've created or
 *  bound one. `revision` is the legacy flat string retained for old
 *  sidecars; `provider_revision` is the durable typed revision used by
 *  current publish/update flows.
 */
export type RemoteIdentity_Deserialize = {
	post_id: string,
	url?: string | null,
	revision?: string | null,
	provider_revision?: ProviderRevision_Deserialize | null,
	capability?: BindingCapability | null,
};

/**
 *  The identity of a post on the remote platform, once we've created or
 *  bound one. `revision` is the legacy flat string retained for old
 *  sidecars; `provider_revision` is the durable typed revision used by
 *  current publish/update flows.
 */
export type RemoteIdentity_Serialize = {
	post_id: string,
	url?: string | null,
	revision?: string | null,
	provider_revision?: ProviderRevision_Serialize | null,
	capability?: BindingCapability | null,
};

export type RenameItemResult = {
	new_path: string,
	migration: RenameMigrationResult,
};

export type RenameMigrationResult = {
	status: RenameMigrationStatus,
	migrated: number,
	conflicts: number,
	errors: string[],
};

export type RenameMigrationStatus = "full_success" | "user_file_renamed_with_metadata_errors" | "idempotent_retry";

export type ResolvedNewFile = {
	template: string,
	detect_from_folder: boolean,
	auto_rename_from_h1: boolean,
	/**  Pinned default directory (`None` means no pin — use last-used instead). */
	default_dir: string | null,
	/**  Last-used directory (`None` means not yet recorded — caller uses project root). */
	last_used_dir: string | null,
};

export type ResolvedPlugins = {
	enabled: { [key in string]: boolean },
};

/**  Fully resolved settings handed to the frontend — no `Option`s. */
export type ResolvedView = {
	sort_mode: string,
	show_hidden_files: boolean,
	wrap_file_names: boolean,
	sidebar_font_size: number,
};

export type RopeDocumentMeta = {
	file_id: string,
	total_lines: number,
	total_bytes: number,
};

export type RopeSnapshot = {
	text: string,
	generation: number,
	total_lines: number,
	total_chars: number,
};

export type RouteResult = {
	/**
	 *  `Some(label)` — Rust has delivered to the winner; FE caller may stop.
	 *  `None` — no window claimed; FE caller should spawn a new window.
	 */
	winner_label: string | null,
};

export type SearchMatch = {
	file_path: string,
	file_name: string,
	line_number: number,
	line_text: string,
	match_start: number,
	match_end: number,
};

export type SnapshotMeta = {
	id: string,
	name: string,
	timestamp: number,
	file_count: number,
	total_bytes: number,
};

export type StyledCopyImage = {
	bytes: number[],
	mime: string,
};

export type SyncConfig = {
	enabled: boolean,
	webdav_url: string,
	username: string,
	password: string,
	interval_minutes: number,
};

export type SyncConfigMasked = {
	enabled: boolean,
	webdav_url: string,
	username: string,
	password: string,
	interval_minutes: number,
};

export type SyncStatus = {
	last_sync: string | null,
	files_uploaded: number,
	files_downloaded: number,
	errors: string[],
	in_progress: boolean,
};

export type TemplateFile = {
	summary: TemplateFileSummary,
	body: string,
};

export type TemplateFileSummary = {
	id: string,
	source: TemplateSource,
	name: string,
	mode: TemplateMode,
	description: string | null,
	defaultFilename: string | null,
};

export type TemplateFrontMatterInput = {
	name: string,
	mode: TemplateMode,
	description: string | null,
	defaultFilename: string | null,
};

/**  Info returned to the frontend for listing templates. */
export type TemplateInfo = {
	id: string,
	name: string,
	description: string,
	category: string,
	/**  Whether this is a built-in template (cannot be deleted). */
	builtin: boolean,
};

export type TemplateMode = "insert" | "new-file";

export type TemplateSource = "bundled" | "project";

/**
 *  Closed enum of reasons a provider might not support an update
 *  call. Deliberately closed (no free-form String) so downstream code
 *  cannot leak provider response text through this variant. Callers
 *  that need finer diagnostics should return
 *  [`PublishError::Server`] or [`PublishError::UnexpectedResponse`]
 *  with `require_success`-scrubbed content instead.
 */
export type UnsupportedUpdateReason =
/**
 *  Provider's API supports post creation but exposes no update
 *  endpoint on this integration flow (e.g. Medium's Integration
 *  Token API is create-only — publish works, PATCH/PUT do not).
 */
"create_only_api" |
/**  Adapter implementation for updates is not yet wired. */
"not_implemented" |
/**  Credential lacks the OAuth scope / capability required to update. */
"insufficient_scope" |
/**
 *  Underlying content type cannot be updated in place (e.g. a Ghost
 *  email newsletter that has already sent).
 */
"immutable_content_type";

/**
 *  Boxed payload for [`PublishError::UpdateConflict`]. Split out
 *  so `Result<_, PublishError>` stays under Clippy's
 *  `result_large_err` size threshold and so the conflict shape can
 *  be inspected as a stand-alone struct in tests and at IPC.
 */
export type UpdateConflictContext = UpdateConflictContext_Serialize | UpdateConflictContext_Deserialize;

/**
 *  Boxed payload for [`PublishError::UpdateConflict`]. Split out
 *  so `Result<_, PublishError>` stays under Clippy's
 *  `result_large_err` size threshold and so the conflict shape can
 *  be inspected as a stand-alone struct in tests and at IPC.
 */
export type UpdateConflictContext_Deserialize = {
	provider: string,
	remote_id: string,
	expected?: ProviderRevision_Deserialize | null,
	actual?: ProviderRevision_Deserialize | null,
};

/**
 *  Boxed payload for [`PublishError::UpdateConflict`]. Split out
 *  so `Result<_, PublishError>` stays under Clippy's
 *  `result_large_err` size threshold and so the conflict shape can
 *  be inspected as a stand-alone struct in tests and at IPC.
 */
export type UpdateConflictContext_Serialize = {
	provider: string,
	remote_id: string,
	expected?: ProviderRevision_Serialize | null,
	actual?: ProviderRevision_Serialize | null,
};

/**
 *  Optional update target on [`PublishInput`]. When present,
 *  adapters MUST update the referenced post instead of creating a
 *  new one. When absent (default), adapters behave exactly as
 *  before — a create call.
 */
export type UpdateTarget = UpdateTarget_Serialize | UpdateTarget_Deserialize;

/**
 *  Optional update target on [`PublishInput`]. When present,
 *  adapters MUST update the referenced post instead of creating a
 *  new one. When absent (default), adapters behave exactly as
 *  before — a create call.
 */
export type UpdateTarget_Deserialize = {
	/**
	 *  Platform post id — same format the adapter returned in
	 *  [`PublishResult::remote_id`].
	 */
	remote_id: string,
	/**
	 *  Revision the caller last observed. Providers that support
	 *  optimistic concurrency (Ghost) require this and reject
	 *  mismatches with [`PublishError::UpdateConflict`]; providers
	 *  that don't (WordPress) accept `None` and always overwrite.
	 */
	expected_revision?: ProviderRevision_Deserialize | null,
};

/**
 *  Optional update target on [`PublishInput`]. When present,
 *  adapters MUST update the referenced post instead of creating a
 *  new one. When absent (default), adapters behave exactly as
 *  before — a create call.
 */
export type UpdateTarget_Serialize = {
	/**
	 *  Platform post id — same format the adapter returned in
	 *  [`PublishResult::remote_id`].
	 */
	remote_id: string,
	/**
	 *  Revision the caller last observed. Providers that support
	 *  optimistic concurrency (Ghost) require this and reject
	 *  mismatches with [`PublishError::UpdateConflict`]; providers
	 *  that don't (WordPress) accept `None` and always overwrite.
	 */
	expected_revision?: ProviderRevision_Serialize | null,
};

/**  Result of a successful upload. */
export type UploadResult = {
	/**  Public URL the user's Markdown should reference. */
	url: string,
	/**
	 *  The remote object key, when the provider chose one we control
	 *  (S3 / OSS / Qiniu). `None` for hosts that pick their own URL
	 *  scheme (imgur, sm.ms).
	 */
	remote_key: string | null,
};

/**
 *  Canonical verified remote identity — the shape Task 21 persists into
 *  `ChannelState.remote` via [`crate::services::publish::sidecar::
 *  update_publish_sidecar`].
 */
export type VerifiedBinding = VerifiedBinding_Serialize | VerifiedBinding_Deserialize;

/**
 *  Canonical verified remote identity — the shape Task 21 persists into
 *  `ChannelState.remote` via [`crate::services::publish::sidecar::
 *  update_publish_sidecar`].
 */
export type VerifiedBinding_Deserialize = {
	/**  The selected channel's stable id (echoed back for the frontend). */
	channel_id: string,
	/**
	 *  Provider discriminant string. Task 20 currently returns verified
	 *  bindings for `"ghost"`, `"wordpress"`, and `"wordpress_com"`;
	 *  Medium legacy binding fails closed because `/v1/me` does not prove
	 *  post ownership.
	 */
	provider: string,
	/**  Server-returned canonical post id. */
	remote_id: string,
	/**
	 *  Server-returned canonical URL (may differ from user input for
	 *  permalink/slug URLs the server percent-encodes).
	 */
	url: string,
	/**
	 *  Provider-typed revision stamp. Absent for Medium and any future
	 *  provider whose API exposes no revision.
	 */
	revision?: ProviderRevision_Deserialize | null,
	/**  Whether Task 21 can expose Update on this channel for this post. */
	capability: BindingCapability,
};

/**
 *  Canonical verified remote identity — the shape Task 21 persists into
 *  `ChannelState.remote` via [`crate::services::publish::sidecar::
 *  update_publish_sidecar`].
 */
export type VerifiedBinding_Serialize = {
	/**  The selected channel's stable id (echoed back for the frontend). */
	channel_id: string,
	/**
	 *  Provider discriminant string. Task 20 currently returns verified
	 *  bindings for `"ghost"`, `"wordpress"`, and `"wordpress_com"`;
	 *  Medium legacy binding fails closed because `/v1/me` does not prove
	 *  post ownership.
	 */
	provider: string,
	/**  Server-returned canonical post id. */
	remote_id: string,
	/**
	 *  Server-returned canonical URL (may differ from user input for
	 *  permalink/slug URLs the server percent-encodes).
	 */
	url: string,
	/**
	 *  Provider-typed revision stamp. Absent for Medium and any future
	 *  provider whose API exposes no revision.
	 */
	revision?: ProviderRevision_Serialize | null,
	/**  Whether Task 21 can expose Update on this channel for this post. */
	capability: BindingCapability,
};

/**  Sidebar / file-tree view preferences. */
export type ViewConfig = ViewConfig_Serialize | ViewConfig_Deserialize;

/**  Sidebar / file-tree view preferences. */
export type ViewConfig_Deserialize = {
	sort_mode?: string | null,
	show_hidden_files?: boolean | null,
	wrap_file_names?: boolean | null,
	sidebar_font_size?: number | null,
};

/**  Sidebar / file-tree view preferences. */
export type ViewConfig_Serialize = {
	sort_mode?: string | null,
	show_hidden_files?: boolean | null,
	wrap_file_names?: boolean | null,
	sidebar_font_size?: number | null,
};

export type ViewportContent = {
	/**  The text content for the requested line range */
	text: string,
	/**  Actual start line (0-indexed) */
	start_line: number,
	/**  Actual end line (exclusive, 0-indexed) */
	end_line: number,
	/**  Total lines in document (can change after edits) */
	total_lines: number,
};

export type WriteFileIfUnchangedResult = "written" | "conflict";

export type WritingConfig = {
	daily_goal?: number,
	auto_save_minutes?: number,
};

export type WritingStatsOverview = {
	daily: DailyStats[],
	total_words: number,
	chapters: ChapterStats[],
	streak_days: number,
	today_words: number,
	today_minutes: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

