// @ts-nocheck
// Auto-generated by tauri-specta

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	readFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_file", { path })),
	writeFile: (path: string, content: string) => typedError<null, string>(__TAURI_INVOKE("write_file", { path, content })),
	/**
	 *  Returns the detected encoding for a file that was previously read via `read_file`.
	 *  Returns `"UTF-8"` if the file is UTF-8 (or was never read).
	 */
	getFileEncoding: (path: string) => typedError<string, string>(__TAURI_INVOKE("get_file_encoding", { path })),
	listDirectory: (path: string, showHidden: boolean | null) => typedError<FileEntry[], string>(__TAURI_INVOKE("list_directory", { path, showHidden })),
	createFile: (parentDir: string, filename: string) => typedError<string, string>(__TAURI_INVOKE("create_file", { parentDir, filename })),
	/**
	 *  Create a scratch file in ~/.cache/novelist/ for single-file mode.
	 *  Filename pattern: `novelist_scratch_<unix_millis>.md`
	 *  This pattern is checked by the frontend to detect unsaved scratch files.
	 *  Returns the absolute path of the created file.
	 */
	createScratchFile: () => typedError<string, string>(__TAURI_INVOKE("create_scratch_file")),
	createDirectory: (parentDir: string, name: string) => typedError<string, string>(__TAURI_INVOKE("create_directory", { parentDir, name })),
	/**
	 *  Rename a file or folder in place.
	 *  When `allow_collision_bump` is Some(true), appends " 2", " 3", … on collision.
	 *  Defaults to error-on-collision when None or Some(false).
	 */
	renameItem: (oldPath: string, newName: string, allowCollisionBump: boolean | null) => typedError<string, string>(__TAURI_INVOKE("rename_item", { oldPath, newName, allowCollisionBump })),
	/**  Emit a global Tauri event so other windows can update their tab state. */
	broadcastFileRenamed: (oldPath: string, newPath: string) => typedError<null, string>(__TAURI_INVOKE("broadcast_file_renamed", { oldPath, newPath })),
	/**
	 *  Move a file or folder into `target_dir`. Auto-numbers on collision
	 *  ("a.md" -> "a 2.md"). Rejects moving a folder into its own descendant.
	 */
	moveItem: (sourcePath: string, targetDir: string) => typedError<string, string>(__TAURI_INVOKE("move_item", { sourcePath, targetDir })),
	deleteItem: (path: string) => typedError<null, string>(__TAURI_INVOKE("delete_item", { path })),
	checkPandoc: () => typedError<PandocStatus_Serialize, string>(__TAURI_INVOKE("check_pandoc")),
	/**
	 *  Persist the user's pandoc binary override. `None` clears it (revert
	 *  to auto-detection). Empty string is treated as `None`.
	 */
	setPandocPath: (path: string | null) => typedError<null, string>(__TAURI_INVOKE("set_pandoc_path", { path })),
	exportProject: (inputFiles: string[], outputPath: string, format: string, extraArgs: string[]) => typedError<string, string>(__TAURI_INVOKE("export_project", { inputFiles, outputPath, format, extraArgs })),
	detectProject: (dirPath: string) => typedError<{
	project: ProjectMeta,
	outline: OutlineConfig,
	writing: WritingConfig,
	/**  Sidebar/file-tree view preferences. Overrides global `~/.novelist/settings.json`. */
	view?: ViewConfig_Serialize,
	/**  New-file template preferences. Overrides global. */
	new_file?: NewFileConfig_Serialize,
	/**  Per-plugin enable flags (deltas from the global default map). */
	plugins?: PluginsConfig,
	/**
	 *  Per-project override for which image host is active. Credentials
	 *  stay in global settings — only the pointer to a configured host
	 *  can be overridden here.
	 */
	active_image_host_id?: string | null,
} | null, string>(__TAURI_INVOKE("detect_project", { dirPath })),
	readProjectConfig: (dirPath: string) => typedError<ProjectConfig_Serialize, string>(__TAURI_INVOKE("read_project_config", { dirPath })),
	/**
	 *  Return effective settings, merging global defaults with an optional
	 *  project overlay. `dir_path = None` returns global-only (scratch mode).
	 */
	getEffectiveSettings: (dirPath: string | null) => typedError<EffectiveSettings, string>(__TAURI_INVOKE("get_effective_settings", { dirPath })),
	/**
	 *  Return raw global defaults from `~/.novelist/settings.json` without
	 *  merging in any project overlay. Used by the frontend to compute plugin
	 *  delta overrides (only entries differing from global are persisted).
	 */
	getGlobalSettings: () => typedError<GlobalSettings_Serialize, string>(__TAURI_INVOKE("get_global_settings")),
	/**
	 *  Patch the global `~/.novelist/settings.json`. Only the `Some(..)` sections
	 *  are replaced; unspecified sections keep their current value on disk.
	 */
	writeGlobalSettings: (view: {
	sort_mode?: string | null,
	show_hidden_files?: boolean | null,
	wrap_file_names?: boolean | null,
	sidebar_font_size?: number | null,
} | null, newFile: {
	template?: string | null,
	detect_from_folder?: boolean | null,
	auto_rename_from_h1?: boolean | null,
	/**
	 *  User-pinned default location for new files. Absolute path. When set,
	 *  Cmd+N always creates here regardless of the recent activity pointer.
	 *  `None` means "follow the last-used tracker."
	 */
	default_dir?: string | null,
	/**
	 *  Live pointer: directory of the most recently created file. Updated
	 *  after every successful create (header button, Cmd+N, per-folder
	 *  context menu). Seeded to the project root on first open.
	 */
	last_used_dir?: string | null,
} | null, plugins: {
	enabled?: { [key in string]: boolean },
} | null) => typedError<null, string>(__TAURI_INVOKE("write_global_settings", { view, newFile, plugins })),
	/**
	 *  Patch `<dir>/.novelist/project.toml`. Only the provided sections are replaced.
	 *  Requires that a `project.toml` already exists (i.e. `dir` is a Novelist project).
	 */
	writeProjectSettings: (dirPath: string, view: {
	sort_mode?: string | null,
	show_hidden_files?: boolean | null,
	wrap_file_names?: boolean | null,
	sidebar_font_size?: number | null,
} | null, newFile: {
	template?: string | null,
	detect_from_folder?: boolean | null,
	auto_rename_from_h1?: boolean | null,
	/**
	 *  User-pinned default location for new files. Absolute path. When set,
	 *  Cmd+N always creates here regardless of the recent activity pointer.
	 *  `None` means "follow the last-used tracker."
	 */
	default_dir?: string | null,
	/**
	 *  Live pointer: directory of the most recently created file. Updated
	 *  after every successful create (header button, Cmd+N, per-folder
	 *  context menu). Seeded to the project root on first open.
	 */
	last_used_dir?: string | null,
} | null, plugins: {
	enabled?: { [key in string]: boolean },
} | null) => typedError<null, string>(__TAURI_INVOKE("write_project_settings", { dirPath, view, newFile, plugins })),
	startFileWatcher: (dirPath: string) => typedError<null, string>(__TAURI_INVOKE("start_file_watcher", { dirPath })),
	stopFileWatcher: () => typedError<null, string>(__TAURI_INVOKE("stop_file_watcher")),
	registerOpenFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("register_open_file", { path })),
	unregisterOpenFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("unregister_open_file", { path })),
	registerWriteIgnore: (path: string) => typedError<null, string>(__TAURI_INVOKE("register_write_ignore", { path })),
	/**
	 *  Polling fallback for external-edit detection.
	 * 
	 *  The notify watcher only covers a single recursively-watched project dir, so
	 *  it misses files opened in single-file mode (no project → no watcher) and can
	 *  miss events on symlinked roots or when the OS coalesces/drops FSEvents. This
	 *  command re-checks every *tracked open file* directly and returns the paths
	 *  whose content changed on disk, so the frontend can reload them on a short
	 *  interval regardless of watcher coverage.
	 * 
	 *  Cheap by design: an mtime stat gates the blake3 hash, so unchanged files
	 *  cost one `stat` each. Self-writes are absorbed via the same 2s `ignore_set`
	 *  the watcher uses — as long as the poll interval is shorter than that window,
	 *  a save is hashed-and-suppressed (its new hash committed) before the window
	 *  expires, so it never surfaces as a spurious external change.
	 */
	pollExternalChanges: () => typedError<string[], string>(__TAURI_INVOKE("poll_external_changes")),
	getRecentProjects: () => typedError<RecentProject[], string>(__TAURI_INVOKE("get_recent_projects")),
	addRecentProject: (path: string, name: string) => typedError<null, string>(__TAURI_INVOKE("add_recent_project", { path, name })),
	removeRecentProject: (path: string) => typedError<null, string>(__TAURI_INVOKE("remove_recent_project", { path })),
	/**  Pin or unpin a single project. Pinned projects always sort above unpinned. */
	setProjectPinned: (path: string, pinned: boolean) => typedError<null, string>(__TAURI_INVOKE("set_project_pinned", { path, pinned })),
	/**
	 *  Reorder recent projects by the given path list. Each path's index in
	 *  `ordered_paths` becomes its new `sort_order`. Paths not in the list keep
	 *  their existing `sort_order`.
	 */
	reorderRecentProjects: (orderedPaths: string[]) => typedError<null, string>(__TAURI_INVOKE("reorder_recent_projects", { orderedPaths })),
	/**  Scan ~/.novelist/plugins/ and return info for each plugin found. */
	listPlugins: () => typedError<PluginInfo[], string>(__TAURI_INVOKE("list_plugins")),
	/**  Load and activate a plugin by its ID. */
	loadPlugin: (pluginId: string) => typedError<null, string>(__TAURI_INVOKE("load_plugin", { pluginId })),
	/**  Unload (deactivate) a plugin. */
	unloadPlugin: (pluginId: string) => typedError<null, string>(__TAURI_INVOKE("unload_plugin", { pluginId })),
	/**
	 *  Unload then re-load a plugin from disk. Used to pick up edits to
	 *  `manifest.toml` / `index.js` without restarting the app.
	 */
	reloadPlugin: (pluginId: string) => typedError<null, string>(__TAURI_INVOKE("reload_plugin", { pluginId })),
	/**  Get all commands registered by active plugins. */
	getPluginCommands: () => typedError<RegisteredCommandInfo[], string>(__TAURI_INVOKE("get_plugin_commands")),
	/**  Execute a registered plugin command. Returns any text replacements the plugin wants to make. */
	invokePluginCommand: (pluginId: string, commandId: string) => typedError<PluginReplacementResult[], string>(__TAURI_INVOKE("invoke_plugin_command", { pluginId, commandId })),
	/**  Update the document state that plugins can read. */
	setPluginDocumentState: (content: string, selectionFrom: number, selectionTo: number, wordCount: number) => typedError<null, string>(__TAURI_INVOKE("set_plugin_document_state", { content, selectionFrom, selectionTo, wordCount })),
	/**
	 *  Enable or disable a plugin (persists to settings file).
	 *  When enabling, also loads the plugin. When disabling, unloads it.
	 */
	setPluginEnabled: (pluginId: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_plugin_enabled", { pluginId, enabled })),
	/**
	 *  Create a minimal plugin at ~/.novelist/plugins/<id>/ with manifest.toml + index.js.
	 *  ID must match `[a-z0-9][a-z0-9-]*`. display_name defaults to id.
	 */
	scaffoldPlugin: (id: string, displayName: string | null) => typedError<string, string>(__TAURI_INVOKE("scaffold_plugin", { id, displayName })),
	/**  Return the absolute path of ~/.novelist/plugins/, creating it if missing. */
	getPluginsDir: () => typedError<string, string>(__TAURI_INVOKE("get_plugins_dir")),
	isPortableMode: () => __TAURI_INVOKE<PortableModeInfo>("is_portable_mode"),
	/**  Open a large file into a Rope. Returns metadata. */
	ropeOpen: (path: string) => typedError<RopeDocumentMeta, string>(__TAURI_INVOKE("rope_open", { path })),
	/**
	 *  Get text for a range of lines. Lines are 0-indexed.
	 *  Returns the text and actual line range (clamped to document bounds).
	 */
	ropeGetLines: (fileId: string, startLine: number, endLine: number) => typedError<ViewportContent, string>(__TAURI_INVOKE("rope_get_lines", { fileId, startLine, endLine })),
	/**
	 *  Apply an edit to the Rope at character offsets.
	 *  `from` and `to` are character (not byte) offsets relative to the full document.
	 *  `insert` is the replacement text (empty string = deletion).
	 */
	ropeApplyEdit: (fileId: string, fromChar: number, toChar: number, insert: string) => typedError<number, string>(__TAURI_INVOKE("rope_apply_edit", { fileId, fromChar, toChar, insert })),
	/**  Save the Rope to disk atomically. */
	ropeSave: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("rope_save", { fileId })),
	/**  Close a Rope document and release memory. */
	ropeClose: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("rope_close", { fileId })),
	/**  Get the character offset for a given line number (0-indexed). */
	ropeLineToChar: (fileId: string, line: number) => typedError<number, string>(__TAURI_INVOKE("rope_line_to_char", { fileId, line })),
	readDraftNote: (projectDir: string, filePath: string) => typedError<string | null, string>(__TAURI_INVOKE("read_draft_note", { projectDir, filePath })),
	writeDraftNote: (projectDir: string, filePath: string, content: string) => typedError<null, string>(__TAURI_INVOKE("write_draft_note", { projectDir, filePath, content })),
	deleteDraftNote: (projectDir: string, filePath: string) => typedError<null, string>(__TAURI_INVOKE("delete_draft_note", { projectDir, filePath })),
	hasDraftNote: (projectDir: string, filePath: string) => typedError<boolean, string>(__TAURI_INVOKE("has_draft_note", { projectDir, filePath })),
	searchInProject: (dirPath: string, query: string) => typedError<SearchMatch[], string>(__TAURI_INVOKE("search_in_project", { dirPath, query })),
	createSnapshot: (projectDir: string, name: string) => typedError<SnapshotMeta, string>(__TAURI_INVOKE("create_snapshot", { projectDir, name })),
	listSnapshots: (projectDir: string) => typedError<SnapshotMeta[], string>(__TAURI_INVOKE("list_snapshots", { projectDir })),
	restoreSnapshot: (projectDir: string, snapshotId: string) => typedError<null, string>(__TAURI_INVOKE("restore_snapshot", { projectDir, snapshotId })),
	deleteSnapshot: (projectDir: string, snapshotId: string) => typedError<null, string>(__TAURI_INVOKE("delete_snapshot", { projectDir, snapshotId })),
	recordWritingStats: (projectDir: string, wordDelta: number, minutes: number) => typedError<null, string>(__TAURI_INVOKE("record_writing_stats", { projectDir, wordDelta, minutes })),
	getWritingStats: (projectDir: string) => typedError<WritingStatsOverview, string>(__TAURI_INVOKE("get_writing_stats", { projectDir })),
	listTemplates: () => typedError<TemplateInfo[], string>(__TAURI_INVOKE("list_templates")),
	createProjectFromTemplate: (templateId: string, projectName: string, parentDir: string, locale: string) => typedError<string, string>(__TAURI_INVOKE("create_project_from_template", { templateId, projectName, parentDir, locale })),
	saveProjectAsTemplate: (projectDir: string, templateName: string) => typedError<TemplateInfo, string>(__TAURI_INVOKE("save_project_as_template", { projectDir, templateName })),
	deleteTemplate: (templateId: string) => typedError<null, string>(__TAURI_INVOKE("delete_template", { templateId })),
	importTemplateZip: (zipPath: string) => typedError<TemplateInfo, string>(__TAURI_INVOKE("import_template_zip", { zipPath })),
	listTemplateFiles: (projectDir: string | null) => typedError<TemplateFileSummary[], string>(__TAURI_INVOKE("list_template_files", { projectDir })),
	readTemplateFile: (source: TemplateSource, id: string, projectDir: string | null) => typedError<TemplateFile, string>(__TAURI_INVOKE("read_template_file", { source, id, projectDir })),
	writeTemplateFile: (projectDir: string, id: string, frontMatter: TemplateFrontMatterInput, body: string) => typedError<TemplateFileSummary, string>(__TAURI_INVOKE("write_template_file", { projectDir, id, frontMatter, body })),
	renameTemplateFile: (projectDir: string, oldId: string, newId: string) => typedError<TemplateFileSummary, string>(__TAURI_INVOKE("rename_template_file", { projectDir, oldId, newId })),
	deleteTemplateFile: (projectDir: string, id: string) => typedError<null, string>(__TAURI_INVOKE("delete_template_file", { projectDir, id })),
	duplicateBundledTemplate: (projectDir: string, bundledId: string, newId: string | null) => typedError<TemplateFileSummary, string>(__TAURI_INVOKE("duplicate_bundled_template", { projectDir, bundledId, newId })),
	/**
	 *  Create a new file in `dir` with `body`. If `filename` already exists,
	 *  auto-bump `stem 2.ext`, `stem 3.ext`, … just like the existing file-tree
	 *  "New file" flow. Returns the resolved absolute path. Used by new-file-mode
	 *  template execution so the frontend does not need to orchestrate sanitize +
	 *  bump + write itself.
	 */
	createFileWithBody: (dir: string, filename: string, body: string) => typedError<string, string>(__TAURI_INVOKE("create_file_with_body", { dir, filename, body })),
	getPendingOpenFiles: () => __TAURI_INVOKE<PendingFile[]>("get_pending_open_files"),
	getPendingOpenProjects: () => __TAURI_INVOKE<string[]>("get_pending_open_projects"),
	/**  Tauri command — FE wrapper around `route_single_file_open`. */
	routeSingleFileOpenCmd: (sourceLabel: string | null, path: string, line: number | null, col: number | null, forceNew: boolean) => __TAURI_INVOKE<RouteResult>("route_single_file_open_cmd", { sourceLabel, path, line, col, forceNew }),
	/**
	 *  Tauri command — each window reports its bid in response to a
	 *  `file-open-bid-request` event.
	 */
	submitFileOpenBid: (bidId: number, windowLabel: string, canClaim: boolean, hasProject: boolean) => typedError<null, string>(__TAURI_INVOKE("submit_file_open_bid", { bidId, windowLabel, canClaim, hasProject })),
	cliShimStatus: () => typedError<CliShimStatus, string>(__TAURI_INVOKE("cli_shim_status")),
	installCliShim: () => typedError<CliShimStatus, string>(__TAURI_INVOKE("install_cli_shim")),
	/**
	 *  Read an image file and return it as a data URI (e.g. `data:image/png;base64,...`).
	 *  Used by the WYSIWYG editor to render local images without the asset protocol.
	 */
	readImageDataUri: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_image_data_uri", { path })),
	/**
	 *  Read a file as raw bytes for upload. The frontend uses this to load
	 *  local image files referenced in Markdown into memory before handing
	 *  them to one of the `upload_image_*` commands.
	 */
	readImageBytes: (path: string) => typedError<number[], string>(__TAURI_INVOKE("read_image_bytes", { path })),
	uploadImageQiniu: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_qiniu", { bytes, filename, mime, config })),
	uploadImageAliyunOss: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_aliyun_oss", { bytes, filename, mime, config })),
	uploadImageS3: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_s3", { bytes, filename, mime, config })),
	uploadImageImgur: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_imgur", { bytes, filename, mime, config })),
	uploadImageSmms: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_smms", { bytes, filename, mime, config })),
	uploadImageCustom: (bytes: number[], filename: string, mime: string, config: ProviderConfig_Deserialize) => typedError<UploadResult, string>(__TAURI_INVOKE("upload_image_custom", { bytes, filename, mime, config })),
	/**  Read the global `image_hosts` settings block. */
	getImageHostSettings: () => typedError<ImageHostSettings_Serialize, string>(__TAURI_INVOKE("get_image_host_settings")),
	/**  Replace the global `image_hosts` settings block atomically. */
	setImageHostSettings: (settings: ImageHostSettings_Deserialize) => typedError<null, string>(__TAURI_INVOKE("set_image_host_settings", { settings })),
	publishToGhost: (input: PublishInput_Deserialize, config: PlatformConfig) => typedError<PublishResult, string>(__TAURI_INVOKE("publish_to_ghost", { input, config })),
	publishToWordpressSelfHosted: (input: PublishInput_Deserialize, config: PlatformConfig) => typedError<PublishResult, string>(__TAURI_INVOKE("publish_to_wordpress_self_hosted", { input, config })),
	publishToWordpressCom: (input: PublishInput_Deserialize, config: PlatformConfig) => typedError<PublishResult, string>(__TAURI_INVOKE("publish_to_wordpress_com", { input, config })),
	publishToMedium: (input: PublishInput_Deserialize, config: PlatformConfig) => typedError<PublishResult, string>(__TAURI_INVOKE("publish_to_medium", { input, config })),
	uploadPostImageGhost: (bytes: number[], filename: string, mime: string, config: PlatformConfig) => typedError<PostImageUploadResult, string>(__TAURI_INVOKE("upload_post_image_ghost", { bytes, filename, mime, config })),
	uploadPostImageWordpressSelfHosted: (bytes: number[], filename: string, mime: string, config: PlatformConfig) => typedError<PostImageUploadResult, string>(__TAURI_INVOKE("upload_post_image_wordpress_self_hosted", { bytes, filename, mime, config })),
	uploadPostImageWordpressCom: (bytes: number[], filename: string, mime: string, config: PlatformConfig) => typedError<PostImageUploadResult, string>(__TAURI_INVOKE("upload_post_image_wordpress_com", { bytes, filename, mime, config })),
	uploadPostImageMedium: (bytes: number[], filename: string, mime: string, config: PlatformConfig) => typedError<PostImageUploadResult, string>(__TAURI_INVOKE("upload_post_image_medium", { bytes, filename, mime, config })),
	/**
	 *  Convert Markdown to HTML via the bundled / system Pandoc binary.
	 *  Used by the frontend orchestrator before submitting to Ghost / WP /
	 *  WP.com (Medium consumes Markdown directly).
	 */
	convertMarkdownToHtml: (markdown: string) => typedError<string, string>(__TAURI_INVOKE("convert_markdown_to_html", { markdown })),
	/**
	 *  Read-only credentials check per platform. Returns a short
	 *  human-friendly status line like "Connected as alice" on success;
	 *  errors propagate with the platform's response body included.
	 */
	verifyPublishChannel: (config: PlatformConfig) => typedError<string, string>(__TAURI_INVOKE("verify_publish_channel", { config })),
	/**
	 *  Fetch existing tag names for the channel (used by the Publish
	 *  dialog's tag autocomplete). Returns an empty vec for platforms
	 *  that don't expose a tag-list API in v0.2.4 (Medium, WordPress —
	 *  can be added later by extending the relevant adapter).
	 */
	listPublishTags: (config: PlatformConfig) => typedError<string[], string>(__TAURI_INVOKE("list_publish_tags", { config })),
	readClipboardImage: () => typedError<ClipboardImage, string>(__TAURI_INVOKE("read_clipboard_image")),
	getPublishSettings: () => typedError<PublishSettings, string>(__TAURI_INVOKE("get_publish_settings")),
	setPublishSettings: (settings: PublishSettings) => typedError<null, string>(__TAURI_INVOKE("set_publish_settings", { settings })),
	/**
	 *  Write raw bytes (passed as base64) to a file. Used by the frontend to save
	 *  pasted/dropped images without UTF-8 encoding corruption.
	 */
	writeBinaryFile: (path: string, base64Data: string) => typedError<null, string>(__TAURI_INVOKE("write_binary_file", { path, base64Data })),
	/**  Reveal a file or folder in the platform's file manager (Finder on macOS). */
	revealInFileManager: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
	/**  Duplicate a file. Returns the path of the new copy. */
	duplicateFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("duplicate_file", { path })),
	/**
	 *  Record a frontend startup phase in the backend tracing log.
	 *  `since_start_ms` is the frontend-observed time relative to the first mark.
	 */
	logStartupPhase: (name: string, sinceStartMs: number | null) => __TAURI_INVOKE<void>("log_startup_phase", { name, sinceStartMs }),
	aiFetchStreamStart: (req: AiFetchRequest) => typedError<string, string>(__TAURI_INVOKE("ai_fetch_stream_start", { req })),
	aiFetchStreamCancel: (streamId: string) => typedError<null, string>(__TAURI_INVOKE("ai_fetch_stream_cancel", { streamId })),
	listAiSessions: (projectDir: string, kind: AiSessionKind) => typedError<AiSessionFile[], string>(__TAURI_INVOKE("list_ai_sessions", { projectDir, kind })),
	readAiSession: (projectDir: string, kind: AiSessionKind, id: string) => typedError<string | null, string>(__TAURI_INVOKE("read_ai_session", { projectDir, kind, id })),
	writeAiSession: (projectDir: string, kind: AiSessionKind, id: string, bodyJson: string) => typedError<null, string>(__TAURI_INVOKE("write_ai_session", { projectDir, kind, id, bodyJson })),
	deleteAiSession: (projectDir: string, kind: AiSessionKind, id: string) => typedError<null, string>(__TAURI_INVOKE("delete_ai_session", { projectDir, kind, id })),
	listAiPromptAssets: (projectDir: string) => typedError<AiPromptAssets, string>(__TAURI_INVOKE("list_ai_prompt_assets", { projectDir })),
	writeAiMemory: (projectDir: string, body: string) => typedError<null, string>(__TAURI_INVOKE("write_ai_memory", { projectDir, body })),
	claudeCliDetect: () => __TAURI_INVOKE<{
	path: string,
	version: string | null,
} | null>("claude_cli_detect"),
	claudeCliSpawn: (req: ClaudeSpawnRequest) => typedError<string, string>(__TAURI_INVOKE("claude_cli_spawn", { req })),
	claudeCliSend: (sessionId: string, line: string) => typedError<null, string>(__TAURI_INVOKE("claude_cli_send", { sessionId, line })),
	claudeCliKill: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("claude_cli_kill", { sessionId })),
	codexCliDetect: () => __TAURI_INVOKE<{
	path: string,
	version: string | null,
} | null>("codex_cli_detect"),
	codexCliTurn: (req: CodexTurnRequest) => typedError<string, string>(__TAURI_INVOKE("codex_cli_turn", { req })),
	codexCliKill: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("codex_cli_kill", { sessionId })),
	refreshMenu: (labels: MenuLabels, recent: RecentEntry[]) => typedError<null, string>(__TAURI_INVOKE("refresh_menu", { labels, recent })),
	/**
	 *  Match the NSWindow's appearance to the app theme so the system-drawn
	 *  title-bar chrome (top-edge highlight, traffic-light hover states) blends
	 *  in. Without this, a dark-themed app on a default-appearance NSWindow gets
	 *  a bright 1px highlight at the very top, because macOS draws the highlight
	 *  for *light* windows.
	 * 
	 *  No-op on non-macOS and on macOS versions predating `NSAppearance` (which
	 *  effectively means no-op if the selector doesn't exist).
	 */
	setWindowAppearance: (dark: boolean) => __TAURI_INVOKE<void>("set_window_appearance", { dark }),
	/**
	 *  Open the native WebView developer tools for this window. Compiled in all
	 *  builds because the `devtools` Cargo feature is enabled by default (see
	 *  Cargo.toml). Gated in the UI behind Developer Mode (F12).
	 */
	openDevtools: () => __TAURI_INVOKE<void>("open_devtools"),
	getSyncConfig: (projectDir: string) => typedError<SyncConfigMasked, string>(__TAURI_INVOKE("get_sync_config", { projectDir })),
	saveSyncConfig: (projectDir: string, config: SyncConfig) => typedError<null, string>(__TAURI_INVOKE("save_sync_config", { projectDir, config })),
	syncNow: (projectDir: string) => typedError<SyncStatus, string>(__TAURI_INVOKE("sync_now", { projectDir })),
	testSyncConnection: (webdavUrl: string, username: string, password: string) => typedError<boolean, string>(__TAURI_INVOKE("test_sync_connection", { webdavUrl, username, password })),
};

/* Types */
export type AiFetchRequest = {
	/**
	 *  Full URL. Must be https:// (http:// allowed only for localhost for
	 *  self-hosted / ollama during development).
	 */
	url: string,
	headers: ([string, string])[],
	/**  Raw JSON body. The caller (plugin) owns the shape — we just POST it. */
	body: string,
	/**
	 *  When true, parse the response as SSE (split on `\n\n`, strip `data: `,
	 *  skip `[DONE]`). When false, buffer the full body and emit one chunk.
	 */
	sse: boolean,
};

export type AiPromptAsset = {
	id: string,
	kind: string,
	path: string,
	name: string,
	content: string,
};

export type AiPromptAssets = {
	commands: AiPromptAsset[],
	skills: AiPromptAsset[],
	memory: AiPromptAsset | null,
};

export type AiSessionFile = {
	id: string,
	kind: AiSessionKind,
	path: string,
	updatedAt: number | null,
};

export type AiSessionKind = "talk" | "agent";

/**
 *  Body format selector. Ghost / WordPress consume HTML; Medium
 *  consumes Markdown natively.
 */
export type BodyFormat = "html" | "markdown";

export type ChannelConfig = {
	/**  Stable UUID. Survives renaming the user-facing label. */
	id: string,
	/**  User-facing label, e.g. "Personal Ghost". */
	name: string,
} & PlatformConfig;

export type ChapterStats = {
	file_name: string,
	file_path: string,
	word_count: number,
};

export type ClaudeSpawnRequest = {
	/**  Override the auto-detected CLI path. */
	cli_path: string | null,
	/**  Working directory for the spawned process. Default: inherit. */
	cwd: string | null,
	system_prompt: string | null,
	/**  Extra `--add-dir` values (plugin usually includes the project root). */
	add_dirs: string[],
	/**
	 *  One of: "acceptEdits", "auto", "bypassPermissions", "default",
	 *  "dontAsk", "plan". Passed through as-is.
	 */
	permission_mode: string | null,
	model: string | null,
	/**  Plugin-owned UUID; must be a valid UUID string on the CLI side. */
	session_uuid: string,
	/**
	 *  Resume an existing CLI conversation instead of creating a new one.
	 *  The CLI rejects `--session-id` values it has already seen (the
	 *  process exits immediately, which surfaced as "Unknown claude
	 *  session" on the next send), so re-spawns of a session that already
	 *  produced output MUST pass `--resume` instead.
	 */
	resume?: boolean,
	/**
	 *  Extra CLI args (escape hatch). Validated against a blocklist of
	 *  flags we manage ourselves.
	 */
	extra_args: string[],
};

/**
 *  Payload emitted as the `cli-open` event on hot path (existing instance
 *  receives a second invocation). The frontend routes folders to new windows
 *  and files to either the focused single-file window or a new window.
 */
export type CliOpenPayload = {
	files: PendingFile[],
	folders: string[],
	force_new_window: boolean,
	/**
	 *  Label of the single window meant to handle this event. On Windows,
	 *  `emit_to` broadcasts to every webview, so the frontend filters on this
	 *  to keep the "single coordinator" semantics (see app-events listeners).
	 */
	target_label: string,
};

export type CliShimStatus = {
	/**  Where the shim would (or does) live on this platform. */
	install_path: string,
	/**  True if the file at `install_path` exists. */
	installed: boolean,
	/**  True if `installed` AND it points at the bundled shim we ship now. */
	up_to_date: boolean,
	/**  Path to the bundled shim — what would be linked/copied. */
	source_path: string,
};

/**
 *  PNG-encoded image bytes pulled from the system clipboard via the
 *  Rust-side `arboard` API. Reading via Rust (instead of the browser's
 *  `navigator.clipboard.read()`) avoids the WebKit/macOS "Paste"
 *  permission prompt that otherwise pops up next to the cursor.
 */
export type ClipboardImage = {
	bytes: number[],
	mime: string,
	width: number,
	height: number,
};

export type CodexTurnRequest = {
	/**  Override the auto-detected CLI path. */
	cli_path: string | null,
	/**  Working directory / agent workspace root. */
	cwd: string | null,
	/**  Model id (passed as `-m`). Empty/None → Codex picks its default. */
	model: string | null,
	/**  Sandbox policy: "read-only", "workspace-write", or "danger-full-access". */
	sandbox: string | null,
	/**  Extra writable directories (`--add-dir`). */
	add_dirs: string[],
	/**  The user prompt for this turn (sent via stdin). */
	prompt: string,
	/**
	 *  When set, resume the existing Codex conversation
	 *  (`codex exec … resume <thread_id>`) instead of starting a new one.
	 */
	resume_thread_id: string | null,
	/**  Caller-owned id used to key the Tauri event channel + kill registry. */
	session_uuid: string,
};

export type DailyStats = {
	date: string,
	words_written: number,
	time_minutes: number,
};

export type DetectedCli = {
	path: string,
	version: string | null,
};

export type EffectiveSettings = {
	view: ResolvedView,
	new_file: ResolvedNewFile,
	plugins: ResolvedPlugins,
	/**  True when a project is open — lets the UI show project-vs-global affordances. */
	is_project_scoped: boolean,
};

export type FileEntry = {
	name: string,
	path: string,
	is_dir: boolean,
	size: number,
	/**  Unix epoch milliseconds; None when filesystem doesn't expose mtime. */
	mtime: number | null,
	/**
	 *  Unix epoch milliseconds for filesystem creation/birth time. None on
	 *  platforms or filesystems that don't expose it (e.g. older ext4).
	 */
	ctime: number | null,
};

/**  Shape written to `~/.novelist/settings.json`. */
export type GlobalSettings = GlobalSettings_Serialize | GlobalSettings_Deserialize;

/**  Shape written to `~/.novelist/settings.json`. */
export type GlobalSettings_Deserialize = {
	view?: ViewConfig_Deserialize,
	new_file?: NewFileConfig_Deserialize,
	plugins?: PluginsConfig,
	/**
	 *  Image-host providers and active-host pointer. Credentials live
	 *  here only — never in per-project settings.
	 */
	image_hosts?: ImageHostSettings_Deserialize,
	/**
	 *  Publish channels (Ghost / WordPress / Medium). Credentials live
	 *  here only — same convention as image_hosts.
	 */
	publish?: PublishSettings,
	/**
	 *  Optional override path to the Pandoc binary. When unset (or
	 *  empty), Novelist auto-detects Pandoc from `$PATH` and common
	 *  install locations. Pandoc is NOT bundled with Novelist — users
	 *  without it installed are pointed at https://pandoc.org/installing.html.
	 */
	pandoc_path?: string | null,
};

/**  Shape written to `~/.novelist/settings.json`. */
export type GlobalSettings_Serialize = {
	view: ViewConfig_Serialize,
	new_file: NewFileConfig_Serialize,
	plugins: PluginsConfig,
	/**
	 *  Image-host providers and active-host pointer. Credentials live
	 *  here only — never in per-project settings.
	 */
	image_hosts: ImageHostSettings_Serialize,
	/**
	 *  Publish channels (Ghost / WordPress / Medium). Credentials live
	 *  here only — same convention as image_hosts.
	 */
	publish: PublishSettings,
	/**
	 *  Optional override path to the Pandoc binary. When unset (or
	 *  empty), Novelist auto-detects Pandoc from `$PATH` and common
	 *  install locations. Pandoc is NOT bundled with Novelist — users
	 *  without it installed are pointed at https://pandoc.org/installing.html.
	 */
	pandoc_path?: string | null,
};

export type HostConfig = HostConfig_Serialize | HostConfig_Deserialize;

export type HostConfig_Deserialize = {
	/**  Stable UUID. Survives renaming the user-facing label. */
	id: string,
	/**  User-facing label, e.g. "Personal R2". */
	name: string,
} & ProviderConfig_Deserialize;

export type HostConfig_Serialize = {
	/**  Stable UUID. Survives renaming the user-facing label. */
	id: string,
	/**  User-facing label, e.g. "Personal R2". */
	name: string,
} & ProviderConfig_Serialize;

export type ImageHostSettings = ImageHostSettings_Serialize | ImageHostSettings_Deserialize;

export type ImageHostSettings_Deserialize = {
	hosts?: HostConfig_Deserialize[],
	active_host_id?: string | null,
	auto_on_paste?: boolean,
};

export type ImageHostSettings_Serialize = {
	hosts: HostConfig_Serialize[],
	active_host_id?: string | null,
	auto_on_paste: boolean,
};

/**
 *  All human-readable labels used in the menu. The frontend builds
 *  this from the i18n store for the current locale. Every field must
 *  be present — fall back to the English string on the frontend if a
 *  translation is missing.
 */
export type MenuLabels = {
	file_menu: string,
	edit_menu: string,
	view_menu: string,
	window_menu: string,
	help_menu: string,
	about_novelist: string,
	settings: string,
	new_file: string,
	new_window: string,
	new_project: string,
	open_file: string,
	open_directory: string,
	open_recent: string,
	no_recent: string,
	open_containing_folder: string,
	switch_project: string,
	rename_file: string,
	move_file: string,
	save_as_template: string,
	export_project: string,
	close_tab: string,
	find_in_project: string,
	go_to_line: string,
	bold: string,
	italic: string,
	strikethrough: string,
	insert_link: string,
	inline_code: string,
	toggle_heading: string,
	copy_rich_text: string,
	copy_plain_text: string,
	simplified_to_traditional: string,
	traditional_to_simplified: string,
	generate_pinyin: string,
	command_palette: string,
	toggle_sidebar: string,
	toggle_outline: string,
	toggle_zen: string,
	toggle_draft: string,
	toggle_snapshot: string,
	toggle_stats: string,
	toggle_template: string,
	toggle_mindmap: string,
	toggle_split: string,
	check_for_updates: string,
};

/**  New-file template preferences. */
export type NewFileConfig = NewFileConfig_Serialize | NewFileConfig_Deserialize;

/**  New-file template preferences. */
export type NewFileConfig_Deserialize = {
	template?: string | null,
	detect_from_folder?: boolean | null,
	auto_rename_from_h1?: boolean | null,
	/**
	 *  User-pinned default location for new files. Absolute path. When set,
	 *  Cmd+N always creates here regardless of the recent activity pointer.
	 *  `None` means "follow the last-used tracker."
	 */
	default_dir?: string | null,
	/**
	 *  Live pointer: directory of the most recently created file. Updated
	 *  after every successful create (header button, Cmd+N, per-folder
	 *  context menu). Seeded to the project root on first open.
	 */
	last_used_dir?: string | null,
};

/**  New-file template preferences. */
export type NewFileConfig_Serialize = {
	template?: string | null,
	detect_from_folder?: boolean | null,
	auto_rename_from_h1?: boolean | null,
	/**
	 *  User-pinned default location for new files. Absolute path. When set,
	 *  Cmd+N always creates here regardless of the recent activity pointer.
	 *  `None` means "follow the last-used tracker."
	 */
	default_dir?: string | null,
	/**
	 *  Live pointer: directory of the most recently created file. Updated
	 *  after every successful create (header button, Cmd+N, per-folder
	 *  context menu). Seeded to the project root on first open.
	 */
	last_used_dir?: string | null,
};

export type OutlineConfig = {
	order?: string[],
};

export type PandocStatus = PandocStatus_Serialize | PandocStatus_Deserialize;

export type PandocStatus_Deserialize = {
	available: boolean,
	version: string | null,
	/**
	 *  Absolute path of the resolved binary, when found. Useful for
	 *  the Settings UI to confirm what we're actually invoking.
	 */
	resolved_path?: string | null,
	/**
	 *  The user's saved override (mirrors `GlobalSettings.pandoc_path`)
	 *  — surfaced so the Settings form can pre-fill the input.
	 */
	override_path?: string | null,
};

export type PandocStatus_Serialize = {
	available: boolean,
	version: string | null,
	/**
	 *  Absolute path of the resolved binary, when found. Useful for
	 *  the Settings UI to confirm what we're actually invoking.
	 */
	resolved_path?: string | null,
	/**
	 *  The user's saved override (mirrors `GlobalSettings.pandoc_path`)
	 *  — surfaced so the Settings form can pre-fill the input.
	 */
	override_path?: string | null,
};

export type PendingFile = {
	path: string,
	line: number | null,
	col: number | null,
};

export type PlatformConfig = { platform: "ghost"; 
/**  Admin URL ending without a slash, e.g. "https://blog.example.com". */
admin_url: string; 
/**  Admin API key in the canonical "<id>:<secret_hex>" form. */
api_key: string } | { platform: "wordpress_self_hosted"; 
/**  Site URL ending without a slash, e.g. "https://blog.example.com". */
site_url: string; username: string; 
/**
 *  Application Password, the 24-char string from WP Admin →
 *  Users → Application Passwords. Spaces optional.
 */
app_password: string } | { platform: "wordpress_com"; 
/**  Site id (numeric) or domain ("myblog.wordpress.com"). */
site_id_or_domain: string; 
/**  OAuth2 access token from developer.wordpress.com. */
access_token: string } | { platform: "medium"; 
/**
 *  Integration token from Settings → Security → Integration
 *  Tokens. The Medium UI for generating new tokens was removed
 *  in late 2024; legacy users only.
 */
token: string };

export type PluginInfo = {
	id: string,
	name: string,
	version: string,
	permissions: string[],
	active: boolean,
	ui: PluginUiConfig | null,
	description: string | null,
	author: string | null,
	icon: string | null,
	builtin: boolean,
	enabled: boolean,
};

export type PluginReplacementResult = {
	from: number,
	to: number,
	text: string,
};

export type PluginUiConfig = {
	type: string,
	entry: string,
	width?: number | null,
	label?: string | null,
	file_extensions?: string[] | null,
};

/**
 *  Per-plugin enable flags. Project-level map stores only entries that
 *  differ from the global default.
 */
export type PluginsConfig = {
	enabled?: { [key in string]: boolean },
};

export type PortableModeInfo = {
	enabled: boolean,
	data_root: string,
};

/**
 *  Returns `(hosted_url, attachment_id_or_zero)`. Only WordPress
 *  returns a non-zero attachment id (used for `featured_media`).
 */
export type PostImageUploadResult = {
	url: string,
	attachment_id: number,
};

export type ProjectConfig = ProjectConfig_Serialize | ProjectConfig_Deserialize;

export type ProjectConfig_Deserialize = {
	project: ProjectMeta,
	outline?: OutlineConfig,
	writing?: WritingConfig,
	/**  Sidebar/file-tree view preferences. Overrides global `~/.novelist/settings.json`. */
	view?: ViewConfig_Deserialize,
	/**  New-file template preferences. Overrides global. */
	new_file?: NewFileConfig_Deserialize,
	/**  Per-plugin enable flags (deltas from the global default map). */
	plugins?: PluginsConfig,
	/**
	 *  Per-project override for which image host is active. Credentials
	 *  stay in global settings — only the pointer to a configured host
	 *  can be overridden here.
	 */
	active_image_host_id?: string | null,
};

export type ProjectConfig_Serialize = {
	project: ProjectMeta,
	outline: OutlineConfig,
	writing: WritingConfig,
	/**  Sidebar/file-tree view preferences. Overrides global `~/.novelist/settings.json`. */
	view?: ViewConfig_Serialize,
	/**  New-file template preferences. Overrides global. */
	new_file?: NewFileConfig_Serialize,
	/**  Per-plugin enable flags (deltas from the global default map). */
	plugins?: PluginsConfig,
	/**
	 *  Per-project override for which image host is active. Credentials
	 *  stay in global settings — only the pointer to a configured host
	 *  can be overridden here.
	 */
	active_image_host_id?: string | null,
};

export type ProjectMeta = {
	name: string,
	type?: string,
	version?: string,
};

export type ProviderConfig = ProviderConfig_Serialize | ProviderConfig_Deserialize;

export type ProviderConfig_Deserialize = ({ provider: "qiniu"; access_key: string; secret_key: string; bucket: string; 
/**  CDN domain that fronts the bucket, e.g. "https://cdn.example.com". */
domain: string }) & { access_key_id?: never; access_key_secret?: never; api_token?: never; bearer?: never; client_id?: never; custom_domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never } | ({ provider: "aliyun_oss"; access_key_id: string; access_key_secret: string; bucket: string; 
/**  Region endpoint, e.g. "oss-cn-hangzhou.aliyuncs.com". */
endpoint: string; custom_domain?: string | null }) & { access_key?: never; api_token?: never; bearer?: never; client_id?: never; domain?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "s3"; access_key_id: string; secret_access_key: string; bucket: string; region: string; 
/**  Set for non-AWS S3-compatible endpoints (R2, MinIO). */
endpoint?: string | null; 
/**  Optional key prefix prepended before the generated object key. */
path_prefix?: string | null; 
/**  Custom CDN domain. Final URL = `<custom_domain>/<key>` when set. */
custom_domain?: string | null }) & { access_key?: never; access_key_secret?: never; api_token?: never; bearer?: never; client_id?: never; domain?: never; post_url?: never; secret_key?: never } | ({ provider: "imgur"; client_id: string }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; api_token?: never; bearer?: never; bucket?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "smms"; api_token?: string | null }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; bearer?: never; bucket?: never; client_id?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "custom"; post_url: string; bearer?: string | null }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; api_token?: never; bucket?: never; client_id?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; region?: never; secret_access_key?: never; secret_key?: never };

export type ProviderConfig_Serialize = ({ provider: "qiniu"; access_key: string; secret_key: string; bucket: string; 
/**  CDN domain that fronts the bucket, e.g. "https://cdn.example.com". */
domain: string }) & { access_key_id?: never; access_key_secret?: never; api_token?: never; bearer?: never; client_id?: never; custom_domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never } | ({ provider: "aliyun_oss"; access_key_id: string; access_key_secret: string; bucket: string; 
/**  Region endpoint, e.g. "oss-cn-hangzhou.aliyuncs.com". */
endpoint: string; custom_domain?: string | null }) & { access_key?: never; api_token?: never; bearer?: never; client_id?: never; domain?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "s3"; access_key_id: string; secret_access_key: string; bucket: string; region: string; 
/**  Set for non-AWS S3-compatible endpoints (R2, MinIO). */
endpoint?: string | null; 
/**  Optional key prefix prepended before the generated object key. */
path_prefix?: string | null; 
/**  Custom CDN domain. Final URL = `<custom_domain>/<key>` when set. */
custom_domain?: string | null }) & { access_key?: never; access_key_secret?: never; api_token?: never; bearer?: never; client_id?: never; domain?: never; post_url?: never; secret_key?: never } | ({ provider: "imgur"; client_id: string }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; api_token?: never; bearer?: never; bucket?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "smms"; api_token?: string | null }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; bearer?: never; bucket?: never; client_id?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; post_url?: never; region?: never; secret_access_key?: never; secret_key?: never } | ({ provider: "custom"; post_url: string; bearer?: string | null }) & { access_key?: never; access_key_id?: never; access_key_secret?: never; api_token?: never; bucket?: never; client_id?: never; custom_domain?: never; domain?: never; endpoint?: never; path_prefix?: never; region?: never; secret_access_key?: never; secret_key?: never };

/**
 *  Inputs handed to a platform adapter's `publish()` function. The
 *  frontend builds this from the publish dialog plus pre-publish
 *  image rewrite.
 */
export type PublishInput = PublishInput_Serialize | PublishInput_Deserialize;

/**
 *  Inputs handed to a platform adapter's `publish()` function. The
 *  frontend builds this from the publish dialog plus pre-publish
 *  image rewrite.
 */
export type PublishInput_Deserialize = {
	title: string,
	/**
	 *  Already-rewritten body. For Ghost / WordPress this is HTML
	 *  (from Pandoc); for Medium this is Markdown.
	 */
	body: string,
	body_format: BodyFormat,
	tags?: string[],
	slug?: string | null,
	excerpt?: string | null,
	/**  Platform-specific status string. See per-platform spec. */
	status: string,
	/**  Already-uploaded feature image URL on the platform. */
	feature_image_url?: string | null,
	/**  WordPress-specific: pre-uploaded media attachment id. */
	featured_media_id?: number | null,
	/**
	 *  Medium-only: when set, post to a publication instead of the
	 *  authenticated user.
	 */
	publication_id?: string | null,
};

/**
 *  Inputs handed to a platform adapter's `publish()` function. The
 *  frontend builds this from the publish dialog plus pre-publish
 *  image rewrite.
 */
export type PublishInput_Serialize = {
	title: string,
	/**
	 *  Already-rewritten body. For Ghost / WordPress this is HTML
	 *  (from Pandoc); for Medium this is Markdown.
	 */
	body: string,
	body_format: BodyFormat,
	tags: string[],
	slug?: string | null,
	excerpt?: string | null,
	/**  Platform-specific status string. See per-platform spec. */
	status: string,
	/**  Already-uploaded feature image URL on the platform. */
	feature_image_url?: string | null,
	/**  WordPress-specific: pre-uploaded media attachment id. */
	featured_media_id?: number | null,
	/**
	 *  Medium-only: when set, post to a publication instead of the
	 *  authenticated user.
	 */
	publication_id?: string | null,
};

/**  Result returned to the frontend on success. */
export type PublishResult = {
	/**  Canonical URL of the new post on the platform. */
	url: string,
	/**  Platform post id (string for portability across platforms). */
	remote_id: string,
};

export type PublishSettings = {
	channels?: ChannelConfig[],
};

/**
 *  An entry shown under the Open Recent submenu. Name is the display
 *  label; path is the absolute directory path used as the menu item ID
 *  suffix.
 */
export type RecentEntry = {
	name: string,
	path: string,
};

export type RecentProject = {
	path: string,
	name: string,
	last_opened: string,
	/**
	 *  `true` keeps the project above all unpinned ones. Optional in the
	 *  persisted JSON so pre-existing files deserialize cleanly.
	 */
	pinned?: boolean,
	/**
	 *  Manual rank within the pinned / unpinned group. Smaller = earlier.
	 *  `None` falls back to `last_opened` order. Optional for back-compat.
	 */
	sort_order?: number | null,
};

export type RegisteredCommandInfo = {
	plugin_id: string,
	command_id: string,
	label: string,
};

export type ResolvedNewFile = {
	template: string,
	detect_from_folder: boolean,
	auto_rename_from_h1: boolean,
	/**  Pinned default directory (`None` means no pin — use last-used instead). */
	default_dir: string | null,
	/**  Last-used directory (`None` means not yet recorded — caller uses project root). */
	last_used_dir: string | null,
};

export type ResolvedPlugins = {
	enabled: { [key in string]: boolean },
};

/**  Fully resolved settings handed to the frontend — no `Option`s. */
export type ResolvedView = {
	sort_mode: string,
	show_hidden_files: boolean,
	wrap_file_names: boolean,
	sidebar_font_size: number,
};

export type RopeDocumentMeta = {
	file_id: string,
	total_lines: number,
	total_bytes: number,
};

export type RouteResult = {
	/**
	 *  `Some(label)` — Rust has delivered to the winner; FE caller may stop.
	 *  `None` — no window claimed; FE caller should spawn a new window.
	 */
	winner_label: string | null,
};

export type SearchMatch = {
	file_path: string,
	file_name: string,
	line_number: number,
	line_text: string,
	match_start: number,
	match_end: number,
};

export type SnapshotMeta = {
	id: string,
	name: string,
	timestamp: number,
	file_count: number,
	total_bytes: number,
};

export type SyncConfig = {
	enabled: boolean,
	webdav_url: string,
	username: string,
	password: string,
	interval_minutes: number,
};

export type SyncConfigMasked = {
	enabled: boolean,
	webdav_url: string,
	username: string,
	password: string,
	interval_minutes: number,
};

export type SyncStatus = {
	last_sync: string | null,
	files_uploaded: number,
	files_downloaded: number,
	errors: string[],
	in_progress: boolean,
};

export type TemplateFile = {
	summary: TemplateFileSummary,
	body: string,
};

export type TemplateFileSummary = {
	id: string,
	source: TemplateSource,
	name: string,
	mode: TemplateMode,
	description: string | null,
	defaultFilename: string | null,
};

export type TemplateFrontMatterInput = {
	name: string,
	mode: TemplateMode,
	description: string | null,
	defaultFilename: string | null,
};

/**  Info returned to the frontend for listing templates. */
export type TemplateInfo = {
	id: string,
	name: string,
	description: string,
	category: string,
	/**  Whether this is a built-in template (cannot be deleted). */
	builtin: boolean,
};

export type TemplateMode = "insert" | "new-file";

export type TemplateSource = "bundled" | "project";

/**  Result of a successful upload. */
export type UploadResult = {
	/**  Public URL the user's Markdown should reference. */
	url: string,
	/**
	 *  The remote object key, when the provider chose one we control
	 *  (S3 / OSS / Qiniu). `None` for hosts that pick their own URL
	 *  scheme (imgur, sm.ms).
	 */
	remote_key: string | null,
};

/**  Sidebar / file-tree view preferences. */
export type ViewConfig = ViewConfig_Serialize | ViewConfig_Deserialize;

/**  Sidebar / file-tree view preferences. */
export type ViewConfig_Deserialize = {
	sort_mode?: string | null,
	show_hidden_files?: boolean | null,
	wrap_file_names?: boolean | null,
	sidebar_font_size?: number | null,
};

/**  Sidebar / file-tree view preferences. */
export type ViewConfig_Serialize = {
	sort_mode?: string | null,
	show_hidden_files?: boolean | null,
	wrap_file_names?: boolean | null,
	sidebar_font_size?: number | null,
};

export type ViewportContent = {
	/**  The text content for the requested line range */
	text: string,
	/**  Actual start line (0-indexed) */
	start_line: number,
	/**  Actual end line (exclusive, 0-indexed) */
	end_line: number,
	/**  Total lines in document (can change after edits) */
	total_lines: number,
};

export type WritingConfig = {
	daily_goal?: number,
	auto_save_minutes?: number,
};

export type WritingStatsOverview = {
	daily: DailyStats[],
	total_words: number,
	chapters: ChapterStats[],
	streak_days: number,
	today_words: number,
	today_minutes: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

