// @ts-nocheck
// Auto-generated by tauri-specta

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	readFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_file", { path })),
	writeFile: (path: string, content: string) => typedError<null, string>(__TAURI_INVOKE("write_file", { path, content })),
	listDirectory: (path: string) => typedError<FileEntry[], string>(__TAURI_INVOKE("list_directory", { path })),
	detectProject: (dirPath: string) => typedError<{
	project: ProjectMeta,
	outline?: OutlineConfig,
	writing?: WritingConfig,
} | null, string>(__TAURI_INVOKE("detect_project", { dirPath })),
	readProjectConfig: (dirPath: string) => typedError<ProjectConfig, string>(__TAURI_INVOKE("read_project_config", { dirPath })),
	startFileWatcher: (dirPath: string) => typedError<null, string>(__TAURI_INVOKE("start_file_watcher", { dirPath })),
	stopFileWatcher: () => typedError<null, string>(__TAURI_INVOKE("stop_file_watcher")),
	registerOpenFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("register_open_file", { path })),
	unregisterOpenFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("unregister_open_file", { path })),
	registerWriteIgnore: (path: string) => typedError<null, string>(__TAURI_INVOKE("register_write_ignore", { path })),
};

/* Types */
export type FileEntry = {
	name: string,
	path: string,
	is_dir: boolean,
	size: number,
};

export type OutlineConfig = {
	order?: string[],
};

export type ProjectConfig = {
	project: ProjectMeta,
	outline?: OutlineConfig,
	writing?: WritingConfig,
};

export type ProjectMeta = {
	name: string,
	type?: string,
	version?: string,
};

export type WritingConfig = {
	daily_goal?: number,
	auto_save_minutes?: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

