mod commands;
mod error;
mod models;
mod services;

pub use error::AppError;

use commands::draft::{delete_draft_note, has_draft_note, read_draft_note, write_draft_note};
use commands::export::{check_pandoc, export_project};
use commands::file::{
    create_directory, create_file, create_scratch_file, delete_item, list_directory, read_file,
    rename_item, search_in_project, write_file,
};
use commands::plugin::{
    get_plugin_commands, invoke_plugin_command, list_plugins, load_plugin,
    set_plugin_document_state, unload_plugin,
};
use commands::project::{detect_project, read_project_config};
use commands::recent::{add_recent_project, get_recent_projects, remove_recent_project};
use commands::snapshot::{create_snapshot, delete_snapshot, list_snapshots, restore_snapshot};
use commands::stats::{get_writing_stats, record_writing_stats};
use commands::sync::{get_sync_config, save_sync_config, sync_now, test_sync_connection};
use services::file_watcher::{
    register_open_file, register_write_ignore, start_file_watcher, stop_file_watcher,
    unregister_open_file, FileWatcherState,
};
use services::plugin_host::sandbox::PluginHostState;
use services::rope_document::{
    rope_apply_edit, rope_close, rope_get_lines, rope_line_to_char, rope_open, rope_save,
    RopeDocumentState,
};
use tauri::Emitter;
use tauri_specta::{collect_commands, Builder};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "novelist=debug".into()),
        )
        .init();

    let builder = Builder::<tauri::Wry>::new().commands(collect_commands![
        read_file,
        write_file,
        list_directory,
        create_file,
        create_scratch_file,
        create_directory,
        rename_item,
        delete_item,
        check_pandoc,
        export_project,
        detect_project,
        read_project_config,
        start_file_watcher,
        stop_file_watcher,
        register_open_file,
        unregister_open_file,
        register_write_ignore,
        get_recent_projects,
        add_recent_project,
        remove_recent_project,
        list_plugins,
        load_plugin,
        unload_plugin,
        get_plugin_commands,
        invoke_plugin_command,
        set_plugin_document_state,
        rope_open,
        rope_get_lines,
        rope_apply_edit,
        rope_save,
        rope_close,
        rope_line_to_char,
        read_draft_note,
        write_draft_note,
        delete_draft_note,
        has_draft_note,
        search_in_project,
        create_snapshot,
        list_snapshots,
        restore_snapshot,
        delete_snapshot,
        record_writing_stats,
        get_writing_stats,
        get_sync_config,
        save_sync_config,
        sync_now,
        test_sync_connection,
    ]);

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::new()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta\n"),
            "../src/lib/ipc/commands.ts",
        )
        .expect("Failed to export typescript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_shell::init())
        .manage(FileWatcherState::new())
        .manage(PluginHostState::new())
        .manage(RopeDocumentState::new())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);

            // Check CLI args for a file path to open in single-file mode
            let handle = app.handle().clone();
            let args: Vec<String> = std::env::args().skip(1).collect();
            let text_extensions = [".md", ".markdown", ".txt"];
            for arg in &args {
                let path = std::path::Path::new(arg);
                if path.exists()
                    && text_extensions
                        .iter()
                        .any(|ext| arg.to_lowercase().ends_with(ext))
                {
                    let file_path = path
                        .canonicalize()
                        .unwrap_or_else(|_| path.to_path_buf())
                        .to_string_lossy()
                        .to_string();
                    // Emit after a short delay so the frontend listener is ready
                    tokio::spawn(async move {
                        tokio::time::sleep(std::time::Duration::from_millis(300)).await;
                        let _ = handle.emit("open-file", file_path);
                    });
                    break;
                }
            }

            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|app, event| {
            // macOS: handle file-open Apple Events (Finder "Open With", double-click)
            #[cfg(target_os = "macos")]
            if let tauri::RunEvent::Opened { urls } = &event {
                let text_extensions = ["md", "markdown", "txt"];
                for url in urls {
                    if let Ok(path) = url.to_file_path() {
                        if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                            if text_extensions.contains(&ext.to_lowercase().as_str()) {
                                let _ = app.emit(
                                    "open-file",
                                    path.to_string_lossy().to_string(),
                                );
                                break;
                            }
                        }
                    }
                }
            }
            // Suppress unused variable warnings on non-macOS
            let _ = (app, event);
        });
}
