mod commands;
mod error;
mod models;
mod services;

pub use error::AppError;

use commands::file::{list_directory, read_file, write_file};
use commands::project::{detect_project, read_project_config};
use services::file_watcher::{
    register_open_file, register_write_ignore, start_file_watcher, stop_file_watcher,
    unregister_open_file, FileWatcherState,
};
use tauri_specta::{collect_commands, Builder};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "novelist=debug".into()),
        )
        .init();

    let builder = Builder::<tauri::Wry>::new().commands(collect_commands![
        read_file,
        write_file,
        list_directory,
        detect_project,
        read_project_config,
        start_file_watcher,
        stop_file_watcher,
        register_open_file,
        unregister_open_file,
        register_write_ignore,
    ]);

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::new()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta\n"),
            "../src/lib/ipc/commands.ts",
        )
        .expect("Failed to export typescript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_shell::init())
        .manage(FileWatcherState::new())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
